package com.company.sqloptimization.infrastructure.queryexecution;

import com.company.sqlforge.common.queryexecution.QueryExecutionAccelerationPlanActivationRequest;
import com.company.sqlforge.common.queryexecution.QueryExecutionAccelerationPlanResponse;
import com.company.sqlforge.common.queryexecution.QueryExecutionAccelerationPlanPauseRequest;

public interface QueryExecutionAccelerationPlanClient {

    QueryExecutionAccelerationPlanResponse activate(QueryExecutionAccelerationPlanActivationRequest request);

    QueryExecutionAccelerationPlanResponse pause(QueryExecutionAccelerationPlanPauseRequest request);
}
