CREATE TABLE IF NOT EXISTS alert_policy (
  policy_id VARCHAR(64) NOT NULL COMMENT '告警策略标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  policy_name VARCHAR(128) NOT NULL COMMENT '可读告警策略名称',
  alert_type VARCHAR(64) NOT NULL COMMENT '告警类型，例如 DATASOURCE_UNAVAILABLE 或 AUDIT_WRITE_EXCEPTION',
  default_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT '默认告警级别：LOW/MEDIUM/HIGH/CRITICAL',
  dedupe_strategy VARCHAR(32) NOT NULL DEFAULT 'TENANT_ALERT_TYPE_TARGET' COMMENT '去重策略基线',
  dedupe_window_seconds INT NOT NULL DEFAULT 900 COMMENT '去重窗口秒数',
  notify_channel VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_EMAIL' COMMENT '通知渠道基线',
  initial_notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT '初始通知状态：SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  owner_role VARCHAR(64) NOT NULL DEFAULT 'TENANT_ADMIN' COMMENT '策略所属角色',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '策略是否启用',
  rule_config_json JSON DEFAULT NULL COMMENT '结构化阈值或匹配器基线 JSON',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  updated_at DATETIME(3) NOT NULL COMMENT '最后更新时间戳',
  PRIMARY KEY (policy_id),
  UNIQUE KEY uk_alert_policy_tenant_type (tenant_id, alert_type),
  KEY idx_alert_policy_tenant_enabled (tenant_id, enabled, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert policy baseline for dedupe, severity, and simulated notify defaults';

CREATE TABLE IF NOT EXISTS alert_event (
  alert_id VARCHAR(64) NOT NULL COMMENT '告警事件标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  alert_type VARCHAR(64) NOT NULL COMMENT '告警类型，例如 DATASOURCE_UNAVAILABLE 或 BENCHMARK_REGRESSION_FAILED',
  alert_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT '告警严重级别：LOW/MEDIUM/HIGH/CRITICAL',
  alert_status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '告警生命周期状态：OPEN/ACKED',
  notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT '通知状态：SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  policy_id VARCHAR(64) DEFAULT NULL COMMENT '所属告警策略标识符',
  dedupe_key VARCHAR(255) NOT NULL COMMENT '租户范围内去重键',
  source_service VARCHAR(64) DEFAULT NULL COMMENT '来源服务编码或来源界面',
  summary VARCHAR(512) NOT NULL COMMENT '面向操作人的告警摘要',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse task标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '关联批次标识符',
  route_decision_id VARCHAR(64) DEFAULT NULL COMMENT '关联路由决策标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联推荐标识符',
  dispatch_event_id VARCHAR(64) DEFAULT NULL COMMENT '关联分发事件标识符',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  datasource_id VARCHAR(128) DEFAULT NULL COMMENT '关联数据源标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  evidence_json JSON DEFAULT NULL COMMENT '结构化证据载荷',
  notify_message VARCHAR(512) DEFAULT NULL COMMENT '最近一次模拟通知结果消息',
  notified_at DATETIME(3) DEFAULT NULL COMMENT '最近一次模拟通知时间戳',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT '确认操作人标识符',
  acked_at DATETIME(3) DEFAULT NULL COMMENT '确认时间戳',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  updated_at DATETIME(3) NOT NULL COMMENT '最后更新时间戳',
  PRIMARY KEY (alert_id),
  KEY idx_alert_event_tenant_status_created (tenant_id, alert_status, created_at),
  KEY idx_alert_event_tenant_dedupe_created (tenant_id, dedupe_key, created_at),
  KEY idx_alert_event_tenant_type_created (tenant_id, alert_type, created_at),
  KEY idx_alert_event_tenant_dispatch (tenant_id, dispatch_event_id, created_at),
  KEY idx_alert_event_tenant_recommendation (tenant_id, recommendation_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert event carrier for simulated notify, dedupe, and future ACK flow';
