CREATE TABLE IF NOT EXISTS optimization_task (
  task_id VARCHAR(64) NOT NULL COMMENT '优化任务标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  task_type VARCHAR(32) NOT NULL COMMENT '优化任务类型：PARSE/REWRITE/ACCELERATION_SUGGESTION',
  sql_text LONGTEXT DEFAULT NULL COMMENT '已提交 SQL 文本快照',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '归一化 SQL 指纹',
  datasource_type VARCHAR(32) NOT NULL COMMENT '数据源类型',
  priority VARCHAR(16) NOT NULL COMMENT '任务优先级',
  parse_depth VARCHAR(16) NOT NULL COMMENT '解析深度',
  callback_url VARCHAR(2048) DEFAULT NULL COMMENT '可选回调 URL',
  requested_suggestion_types_json JSON DEFAULT NULL COMMENT '请求的加速建议类型 JSON',
  status VARCHAR(16) NOT NULL COMMENT 'Task 状态：QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  current_phase VARCHAR(32) NOT NULL COMMENT '当前任务阶段',
  progress_percent INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
  summary TEXT DEFAULT NULL COMMENT '任务完成时的摘要',
  error_code INT DEFAULT NULL COMMENT '失败码',
  error_message VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的失败消息',
  error_suggested_action VARCHAR(512) DEFAULT NULL COMMENT '建议的后续处理动作',
  error_retryable TINYINT(1) DEFAULT NULL COMMENT '失败是否可重试',
  status_history_json JSON NOT NULL COMMENT '有序状态流转历史 JSON',
  submitted_at DATETIME(3) NOT NULL COMMENT '提交时间戳',
  started_at DATETIME(3) DEFAULT NULL COMMENT 'Worker 启动时间戳',
  finished_at DATETIME(3) DEFAULT NULL COMMENT '结束时间戳',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (task_id),
  KEY idx_optimization_task_status_submitted (status, submitted_at),
  KEY idx_optimization_task_tenant_time (tenant_id, create_time),
  KEY idx_optimization_task_fingerprint (sql_fingerprint)
);
