CREATE TABLE IF NOT EXISTS report_batch (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表目录批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  batch_name VARCHAR(255) NOT NULL COMMENT '批次显示名称',
  file_type VARCHAR(16) NOT NULL COMMENT '来源文件类型，模拟来源当前为 TXT',
  report_code_field VARCHAR(128) NOT NULL COMMENT '包含 report_code 的列名',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码覆盖值',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据，例如 DEV/UAT/PROD',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型，例如 TXT_MOCK_SOURCE',
  status VARCHAR(32) NOT NULL COMMENT '当前批次状态',
  total_reports INT NOT NULL DEFAULT 0 COMMENT '导入报表数',
  resolved_reports INT NOT NULL DEFAULT 0 COMMENT '已解析报表数',
  failed_reports INT NOT NULL DEFAULT 0 COMMENT '失败报表数',
  status_history_json JSON NOT NULL COMMENT '批次状态历史载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '批次创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id),
  KEY idx_report_batch_tenant_status_created (tenant_id, status, created_at),
  KEY idx_report_batch_tenant_code (tenant_id, report_code_field)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog batch baseline';

CREATE TABLE IF NOT EXISTS report_batch_item (
  item_id VARCHAR(64) NOT NULL COMMENT '报表批次条目标识符',
  batch_id VARCHAR(64) NOT NULL COMMENT '所属报表批次标识符',
  sequence_number INT NOT NULL COMMENT '上传批次内从 1 开始的序号',
  report_code VARCHAR(128) NOT NULL COMMENT '报表编码',
  report_name VARCHAR(255) DEFAULT NULL COMMENT '报表名称',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '该行解析得到的数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  source_file_line VARCHAR(512) DEFAULT NULL COMMENT '原始来源行或 CSV 载荷摘要',
  sql_column_name VARCHAR(128) DEFAULT NULL COMMENT '提供该 SQL 的来源电子表格列',
  sql_ordinal_in_report INT DEFAULT NULL COMMENT '同一 report_code 内从 1 开始的 SQL 序号',
  sql_text MEDIUMTEXT DEFAULT NULL COMMENT '解析后的 SQL 文本',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '解析任务标识符',
  structure_syntax_status VARCHAR(32) DEFAULT NULL COMMENT '结构解析语法状态',
  access_service_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析提供方状态',
  access_connection_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析连接状态',
  failure_reason VARCHAR(128) DEFAULT NULL COMMENT '失败或降级原因',
  status VARCHAR(32) NOT NULL COMMENT '当前条目状态',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景摘要载荷',
  logical_object_keys_json JSON DEFAULT NULL COMMENT '逻辑对象命中摘要载荷',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (item_id),
  KEY idx_report_batch_item_batch_seq (batch_id, sequence_number),
  KEY idx_report_batch_item_batch_status (batch_id, status),
  KEY idx_report_batch_item_report (batch_id, report_code),
  KEY idx_report_batch_item_report_sql (batch_id, report_code, sql_ordinal_in_report)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog imported records and parse evidence';
