CREATE TABLE IF NOT EXISTS alert_policy (
  policy_id VARCHAR(64) NOT NULL COMMENT 'Alert policy identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Tenant identifier',
  policy_name VARCHAR(128) NOT NULL COMMENT 'Readable alert policy name',
  alert_type VARCHAR(64) NOT NULL COMMENT 'Alert type such as DATASOURCE_UNAVAILABLE or AUDIT_WRITE_EXCEPTION',
  default_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Default alert level: LOW/MEDIUM/HIGH/CRITICAL',
  dedupe_strategy VARCHAR(32) NOT NULL DEFAULT 'TENANT_ALERT_TYPE_TARGET' COMMENT 'Dedupe strategy baseline',
  dedupe_window_seconds INT NOT NULL DEFAULT 900 COMMENT 'Deduplication window in seconds',
  notify_channel VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_EMAIL' COMMENT 'Notify channel baseline',
  initial_notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT 'Initial notification status: SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  owner_role VARCHAR(64) NOT NULL DEFAULT 'TENANT_ADMIN' COMMENT 'Owning role for the policy',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether the policy is enabled',
  rule_config_json JSON DEFAULT NULL COMMENT 'Structured threshold or matcher baseline JSON',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Operator identifier',
  created_at DATETIME(3) NOT NULL COMMENT 'Creation timestamp',
  updated_at DATETIME(3) NOT NULL COMMENT 'Last update timestamp',
  PRIMARY KEY (policy_id),
  UNIQUE KEY uk_alert_policy_tenant_type (tenant_id, alert_type),
  KEY idx_alert_policy_tenant_enabled (tenant_id, enabled, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert policy baseline for dedupe, severity, and simulated notify defaults';

CREATE TABLE IF NOT EXISTS alert_event (
  alert_id VARCHAR(64) NOT NULL COMMENT 'Alert event identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Tenant identifier',
  alert_type VARCHAR(64) NOT NULL COMMENT 'Alert type such as DATASOURCE_UNAVAILABLE or BENCHMARK_REGRESSION_FAILED',
  alert_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Alert severity level: LOW/MEDIUM/HIGH/CRITICAL',
  alert_status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT 'Alert lifecycle status: OPEN/ACKED',
  notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT 'Notification status: SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  policy_id VARCHAR(64) DEFAULT NULL COMMENT 'Owning alert policy identifier',
  dedupe_key VARCHAR(255) NOT NULL COMMENT 'Tenant-scoped dedupe key',
  source_service VARCHAR(64) DEFAULT NULL COMMENT 'Origin service code or source surface',
  summary VARCHAR(512) NOT NULL COMMENT 'Alert summary for operators',
  history_id VARCHAR(64) DEFAULT NULL COMMENT 'Related governance query history identifier',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Related parse task identifier',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT 'Related batch identifier',
  route_decision_id VARCHAR(64) DEFAULT NULL COMMENT 'Related routing decision identifier',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT 'Related recommendation identifier',
  dispatch_event_id VARCHAR(64) DEFAULT NULL COMMENT 'Related dispatch event identifier',
  report_code VARCHAR(128) DEFAULT NULL COMMENT 'Related report code',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT 'Related logical object key',
  datasource_id VARCHAR(128) DEFAULT NULL COMMENT 'Related datasource identifier',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT 'Normalized SQL fingerprint',
  evidence_json JSON DEFAULT NULL COMMENT 'Structured evidence payload',
  notify_message VARCHAR(512) DEFAULT NULL COMMENT 'Latest simulated notification result message',
  notified_at DATETIME(3) DEFAULT NULL COMMENT 'Last simulated notification timestamp',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT 'Acknowledging operator identifier',
  acked_at DATETIME(3) DEFAULT NULL COMMENT 'Acknowledgement timestamp',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Operator identifier',
  created_at DATETIME(3) NOT NULL COMMENT 'Creation timestamp',
  updated_at DATETIME(3) NOT NULL COMMENT 'Last update timestamp',
  PRIMARY KEY (alert_id),
  KEY idx_alert_event_tenant_status_created (tenant_id, alert_status, created_at),
  KEY idx_alert_event_tenant_dedupe_created (tenant_id, dedupe_key, created_at),
  KEY idx_alert_event_tenant_type_created (tenant_id, alert_type, created_at),
  KEY idx_alert_event_tenant_dispatch (tenant_id, dispatch_event_id, created_at),
  KEY idx_alert_event_tenant_recommendation (tenant_id, recommendation_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert event carrier for simulated notify, dedupe, and future ACK flow';
