CREATE TABLE IF NOT EXISTS acceleration_candidate (
  candidate_id VARCHAR(64) NOT NULL COMMENT 'Acceleration candidate identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  source_type VARCHAR(32) NOT NULL COMMENT 'PARSE/QUERY source family',
  source_kind VARCHAR(64) NOT NULL COMMENT 'Normalized source kind',
  source_id VARCHAR(128) NOT NULL COMMENT 'Source object identifier',
  history_id VARCHAR(64) DEFAULT NULL COMMENT 'Related governance query history identifier',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT 'Related sql_parse_history identifier',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Related parse task identifier',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT 'Related parse/report batch identifier',
  batch_item_id VARCHAR(64) DEFAULT NULL COMMENT 'Related parse/report batch item identifier',
  benchmark_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Related benchmark task identifier',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Related optimization task identifier',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT 'Normalized SQL fingerprint',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT 'Related datasource code',
  stage VARCHAR(32) DEFAULT NULL COMMENT 'Source environment or lifecycle stage',
  report_code VARCHAR(128) DEFAULT NULL COMMENT 'Related report code',
  candidate_type VARCHAR(32) NOT NULL DEFAULT 'ACCELERATION_AND_REWRITE' COMMENT 'ACCELERATION/REWRITE/ACCELERATION_AND_REWRITE',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/RECOMMENDED/PLAN_CREATED/REJECTED/INVALID/CANCELLED',
  confidence DECIMAL(5,4) DEFAULT NULL COMMENT 'Static confidence score, not runtime benefit proof',
  priority INT DEFAULT NULL COMMENT 'Candidate priority for operator sorting',
  evidence_level VARCHAR(32) NOT NULL COMMENT 'STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED',
  schema_version VARCHAR(32) DEFAULT NULL COMMENT 'Candidate payload schema version',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Candidate creator',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  source_evidence_json JSON DEFAULT NULL COMMENT 'Normalized source evidence',
  issue_evidence_json JSON DEFAULT NULL COMMENT 'Static parse issue evidence',
  runtime_evidence_json JSON DEFAULT NULL COMMENT 'Runtime evidence summary only',
  benefit_estimate_json JSON DEFAULT NULL COMMENT 'Estimated benefit evidence, not real gain proof',
  cost_estimate_json JSON DEFAULT NULL COMMENT 'Estimated implementation or validation cost',
  risk_json JSON DEFAULT NULL COMMENT 'Risk evidence and manual review hints',
  PRIMARY KEY (candidate_id),
  KEY idx_acc_candidate_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_candidate_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_acc_candidate_history (tenant_id, history_id),
  KEY idx_acc_candidate_parse_history (tenant_id, parse_history_id),
  KEY idx_acc_candidate_optimization_task (tenant_id, optimization_task_id),
  KEY idx_acc_candidate_benchmark_task (tenant_id, benchmark_task_id),
  KEY idx_acc_candidate_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_candidate_report (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed acceleration and rewrite candidate persistence';

CREATE TABLE IF NOT EXISTS sql_rewrite_record (
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT 'SQL rewrite record identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT 'Related acceleration recommendation identifier',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Related optimization task identifier',
  source_type VARCHAR(32) NOT NULL COMMENT 'PARSE/QUERY source family',
  source_kind VARCHAR(64) NOT NULL COMMENT 'Normalized source kind',
  source_id VARCHAR(128) NOT NULL COMMENT 'Source object identifier',
  evidence_level VARCHAR(32) NOT NULL COMMENT 'Evidence level for the rewrite source',
  history_id VARCHAR(64) DEFAULT NULL COMMENT 'Related governance query history identifier',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT 'Related sql_parse_history identifier',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT 'Normalized SQL fingerprint',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT 'Related datasource code',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/RECOMMENDED/APPROVED/APPLIED/PAUSED/ROLLED_BACK/DEPRECATED/CANCELLED',
  validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT 'NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 if auto apply is allowed by governance',
  manual_review_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 if manual review is required before applying',
  validation_policy_id VARCHAR(64) DEFAULT NULL COMMENT 'Validation policy identifier',
  last_validation_run_id VARCHAR(64) DEFAULT NULL COMMENT 'Last validation run identifier',
  last_compared_at DATETIME DEFAULT NULL COMMENT 'Last comparison timestamp',
  alert_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/OPEN/ACKED/RESOLVED/SUPPRESSED',
  original_sql_text MEDIUMTEXT NOT NULL COMMENT 'Original SQL text for governed diff and trace',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT 'Recommended SQL text for governed diff and trace',
  executed_sql_text MEDIUMTEXT DEFAULT NULL COMMENT 'Executed SQL text when a governed application path exists',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Record creator',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  rule_chain_json JSON DEFAULT NULL COMMENT 'Applied rewrite rule chain evidence',
  diff_summary_json JSON DEFAULT NULL COMMENT 'Diff summary evidence',
  risk_json JSON DEFAULT NULL COMMENT 'Risk and review evidence',
  trace_refs_json JSON DEFAULT NULL COMMENT 'Cross-service trace references',
  PRIMARY KEY (rewrite_record_id),
  KEY idx_rewrite_record_tenant_status_created (tenant_id, status, created_at),
  KEY idx_rewrite_record_validation (tenant_id, validation_status, last_compared_at),
  KEY idx_rewrite_record_recommendation (tenant_id, recommendation_id),
  KEY idx_rewrite_record_optimization_task (tenant_id, optimization_task_id),
  KEY idx_rewrite_record_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_rewrite_record_history (tenant_id, history_id),
  KEY idx_rewrite_record_parse_history (tenant_id, parse_history_id),
  KEY idx_rewrite_record_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_rewrite_record_last_run (tenant_id, last_validation_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite record persistence';

CREATE TABLE IF NOT EXISTS rewrite_validation_run (
  validation_run_id VARCHAR(64) NOT NULL COMMENT 'Rewrite validation run identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT 'Referenced rewrite record identifier',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT 'Related acceleration recommendation identifier',
  history_id VARCHAR(64) DEFAULT NULL COMMENT 'Related governance query history identifier',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT 'Normalized SQL fingerprint',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  comparison_status VARCHAR(32) NOT NULL DEFAULT 'NOT_COMPARED' COMMENT 'NOT_COMPARED/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  difference_type VARCHAR(64) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/SCHEMA_DIFF/ROW_COUNT_DIFF/KEY_SET_DIFF/ORDER_DIFF/VALUE_DIFF/CHECKSUM_DIFF/TIMEZONE_OR_PRECISION_DIFF/UNKNOWN',
  auto_apply_paused TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 if validation paused automatic application',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Validation start timestamp',
  finished_at DATETIME DEFAULT NULL COMMENT 'Validation finish timestamp',
  comparison_policy_json JSON DEFAULT NULL COMMENT 'Validation policy snapshot',
  original_result_digest_json JSON DEFAULT NULL COMMENT 'Original SQL result digest, not full result set',
  recommended_result_digest_json JSON DEFAULT NULL COMMENT 'Recommended SQL result digest, not full result set',
  difference_sample_json JSON DEFAULT NULL COMMENT 'Limited difference sample evidence',
  execution_evidence_json JSON DEFAULT NULL COMMENT 'Readonly execution or benchmark evidence summary',
  PRIMARY KEY (validation_run_id),
  KEY idx_validation_run_rewrite_started (tenant_id, rewrite_record_id, started_at),
  KEY idx_validation_run_recommendation (tenant_id, recommendation_id),
  KEY idx_validation_run_history (tenant_id, history_id),
  KEY idx_validation_run_status_started (tenant_id, status, started_at),
  KEY idx_validation_run_comparison (tenant_id, comparison_status, difference_type),
  KEY idx_validation_run_fingerprint (tenant_id, sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite validation run persistence';
