CREATE TABLE IF NOT EXISTS dispatch_event (
  dispatch_event_id VARCHAR(64) NOT NULL COMMENT 'Dispatch event identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  recommendation_id VARCHAR(64) NOT NULL COMMENT 'Source recommendation identifier',
  dispatch_type VARCHAR(32) NOT NULL COMMENT 'REWRITE_SQL/ACCELERATION_SQL/CREATE_TABLE_SQL/PREWARM_SQL/MAINTENANCE_SQL',
  dispatch_payload_json JSON NOT NULL COMMENT 'Pull-based dispatch payload for external loading or maintenance module',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT 'Target execution engine',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT 'Target datasource code',
  report_code VARCHAR(128) DEFAULT NULL COMMENT 'Related report code',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT 'Related logical object key',
  status VARCHAR(32) NOT NULL COMMENT 'CREATED/PUBLISHED/PULLED/ACKED/FAILED',
  pulled_by VARCHAR(64) DEFAULT NULL COMMENT 'External module or operator that pulled the event',
  pulled_at DATETIME DEFAULT NULL COMMENT 'Pull timestamp',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT 'External module or operator that acked the event',
  acked_at DATETIME DEFAULT NULL COMMENT 'Ack timestamp',
  failed_by VARCHAR(64) DEFAULT NULL COMMENT 'External module or operator that failed the event',
  failed_at DATETIME DEFAULT NULL COMMENT 'Failure timestamp',
  result_message TEXT DEFAULT NULL COMMENT 'Ack/fail message from external module',
  status_history_json JSON NOT NULL COMMENT 'Append-only state transition evidence',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Dispatch creator',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (dispatch_event_id),
  KEY idx_dispatch_event_tenant_status_created (tenant_id, status, created_at),
  KEY idx_dispatch_event_recommendation (tenant_id, recommendation_id),
  KEY idx_dispatch_event_report_code (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pull-based recommendation dispatch state machine';
