ALTER TABLE acceleration_recommendation
  ADD COLUMN source_type VARCHAR(32) DEFAULT NULL COMMENT '用于推荐可追踪性的 PARSE/QUERY 来源类型' AFTER status,
  ADD COLUMN source_kind VARCHAR(64) DEFAULT NULL COMMENT '治理来源类型，例如 STRUCTURE_PARSE/QUERY_HISTORY' AFTER source_type,
  ADD COLUMN source_id VARCHAR(128) DEFAULT NULL COMMENT '与来源类型/种类配对的规范来源标识符' AFTER source_kind,
  ADD COLUMN evidence_level VARCHAR(32) DEFAULT NULL COMMENT '证据level：STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED' AFTER source_id,
  ADD COLUMN schema_version VARCHAR(64) NOT NULL DEFAULT 'SQL_RECOMMENDATION_RULE_MODEL_V1' COMMENT '推荐规则输出模式版本' AFTER evidence_level,
  ADD COLUMN rule_chain_json JSON DEFAULT NULL COMMENT '已应用或已选择的推荐规则链证据' AFTER schema_version,
  ADD COLUMN unapplied_rules_json JSON DEFAULT NULL COMMENT '已考虑但未应用的规则及原因证据' AFTER rule_chain_json,
  ADD COLUMN preconditions_json JSON DEFAULT NULL COMMENT '校验或后续应用前所需的前置条件' AFTER unapplied_rules_json,
  ADD COLUMN semantic_risks_json JSON DEFAULT NULL COMMENT '需要校验或人工评审的语义风险' AFTER preconditions_json,
  ADD COLUMN expected_benefit_json JSON DEFAULT NULL COMMENT '静态预估收益证据，非真实执行收益' AFTER semantic_risks_json,
  ADD COLUMN estimated_cost_json JSON DEFAULT NULL COMMENT '静态预估成本与治理跟进证据' AFTER expected_benefit_json,
  ADD COLUMN confidence INT DEFAULT NULL COMMENT '静态模型置信分 0-100' AFTER estimated_cost_json,
  ADD COLUMN validation_method VARCHAR(64) DEFAULT NULL COMMENT '批准或后续应用前要求的校验方法' AFTER confidence,
  ADD COLUMN validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT '校验状态：NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED' AFTER validation_method,
  ADD COLUMN auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '校验后是否允许后续自动应用' AFTER validation_status,
  ADD COLUMN manual_review_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT '推荐是否需要人工评审' AFTER auto_apply_allowed,
  ADD KEY idx_acc_reco_source (tenant_id, source_type, source_kind, source_id),
  ADD KEY idx_acc_reco_validation (tenant_id, validation_status, manual_review_required);
