CREATE TABLE IF NOT EXISTS parse_batch_item (
  item_id VARCHAR(64) NOT NULL COMMENT '解析批次条目标识符',
  batch_id VARCHAR(64) NOT NULL COMMENT '所属解析批次标识符',
  sequence_number INT NOT NULL COMMENT '上传批次内从 1 开始的序号',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '带入治理上下文的可选报表编码',
  report_name VARCHAR(255) DEFAULT NULL COMMENT '可选报表显示名称',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '该行解析得到的数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据，例如 DEV/UAT/PROD',
  biz_date VARCHAR(32) DEFAULT NULL COMMENT '执行日期元数据',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  owner VARCHAR(128) DEFAULT NULL COMMENT '负责人元数据',
  tags VARCHAR(255) DEFAULT NULL COMMENT '自由格式标签',
  sql_text MEDIUMTEXT NOT NULL COMMENT '解析后的 SQL 文本',
  sql_template_text MEDIUMTEXT DEFAULT NULL COMMENT '预备 SQL 模板文本',
  bind_parameters_json JSON DEFAULT NULL COMMENT '脱敏后的绑定参数载荷',
  binding_mode VARCHAR(32) DEFAULT NULL COMMENT 'Binding 模式，例如 POSITIONAL/NAMED',
  status VARCHAR(32) NOT NULL COMMENT '终态条目状态',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '结构/访问解析任务标识符',
  structure_syntax_status VARCHAR(32) DEFAULT NULL COMMENT '结构解析语法状态',
  access_service_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析提供方状态',
  access_connection_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析连接状态',
  failure_reason VARCHAR(128) DEFAULT NULL COMMENT '失败或降级原因',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景摘要载荷',
  logical_object_keys_json JSON DEFAULT NULL COMMENT '逻辑对象命中摘要载荷',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (item_id),
  KEY idx_parse_batch_item_batch_seq (batch_id, sequence_number),
  KEY idx_parse_batch_item_batch_status (batch_id, status),
  KEY idx_parse_batch_item_report (batch_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bulk parse batch imported records and parse evidence';
