CREATE TABLE IF NOT EXISTS acceleration_recommendation (
  recommendation_id VARCHAR(64) NOT NULL COMMENT '推荐标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_type VARCHAR(32) NOT NULL COMMENT '推荐类型：REWRITE/ACCELERATION/CREATE_TABLE/PREWARM/MAINTENANCE',
  source_sql_id VARCHAR(64) DEFAULT NULL COMMENT '来源 SQL、解析条目、历史或任务标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  source_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '原始 SQL 文本或模板',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '推荐 SQL、建表 SQL、预热 SQL 或维护 SQL',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '目标执行引擎',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT '目标数据源编码',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  summary VARCHAR(512) DEFAULT NULL COMMENT '推荐摘要',
  reason TEXT DEFAULT NULL COMMENT '推荐原因',
  expected_gain VARCHAR(512) DEFAULT NULL COMMENT '预期收益描述',
  benefit_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '收益级别：UNKNOWN/LOW/MEDIUM/HIGH',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '风险级别：UNKNOWN/LOW/MEDIUM/HIGH/CRITICAL',
  risk_summary TEXT DEFAULT NULL COMMENT '风险摘要与约束',
  requires_dispatch TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示需要外部装载/分发协同',
  status VARCHAR(32) NOT NULL DEFAULT 'RECOMMENDED' COMMENT '推荐状态：RECOMMENDED/REVIEWING/DISPATCH_READY/CANCELLED；SQLForge 内无已执行状态',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '推荐创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (recommendation_id),
  KEY idx_acc_reco_tenant_type_created (tenant_id, recommendation_type, created_at),
  KEY idx_acc_reco_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_reco_sql_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_reco_report_code (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Read-only SQL acceleration and rewrite recommendation catalog';
