CREATE TABLE IF NOT EXISTS alert_notification_log (
  notification_log_id VARCHAR(96) NOT NULL COMMENT '告警通知日志标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  alert_id VARCHAR(64) NOT NULL COMMENT '作为持久化来源使用的告警事件标识符',
  source_alert_id VARCHAR(64) DEFAULT NULL COMMENT '通知被抑制时的原始去重来源告警标识符',
  dedupe_key VARCHAR(255) NOT NULL COMMENT '租户范围内去重键',
  notify_channel VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_EMAIL' COMMENT '通知渠道，第一阶段仅模拟',
  delivery_status VARCHAR(32) NOT NULL COMMENT '投递状态：SIMULATED_SENT/DEDUPE_SUPPRESSED/SIMULATED_FAILED',
  template_code VARCHAR(64) NOT NULL COMMENT '已渲染模板标识符',
  message_subject VARCHAR(255) NOT NULL COMMENT '已渲染模拟消息主题',
  message_body TEXT NOT NULL COMMENT '已渲染模拟消息正文',
  delivery_summary VARCHAR(512) DEFAULT NULL COMMENT '投递或抑制摘要',
  payload_json JSON DEFAULT NULL COMMENT '通知模拟或去重抑制证据的结构化载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  PRIMARY KEY (notification_log_id),
  KEY idx_alert_notification_tenant_alert_created (tenant_id, alert_id, created_at),
  KEY idx_alert_notification_tenant_dedupe_created (tenant_id, dedupe_key, created_at),
  KEY idx_alert_notification_tenant_status_created (tenant_id, delivery_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Simulated alert notification and dedupe suppression log';
