ALTER TABLE sql_rewrite_record
  ADD COLUMN review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW' COMMENT '人工评审状态：PENDING_REVIEW/APPROVED/REJECTED/CHANGES_REQUESTED' AFTER manual_review_required,
  ADD COLUMN review_note VARCHAR(512) DEFAULT NULL COMMENT '批准或驳回的人审备注' AFTER review_status,
  ADD COLUMN reviewed_by VARCHAR(64) DEFAULT NULL COMMENT '人工评审人标识符' AFTER review_note,
  ADD COLUMN reviewed_at DATETIME DEFAULT NULL COMMENT '人工评审时间戳' AFTER reviewed_by,
  ADD COLUMN publish_status VARCHAR(32) NOT NULL DEFAULT 'UNPUBLISHED' COMMENT '发布状态：UNPUBLISHED/PUBLISHING/PUBLISHED/PAUSED/UNPUBLISHING/UNPUBLISH_FAILED/PUBLISH_FAILED' AFTER reviewed_at,
  ADD COLUMN runtime_binding_id VARCHAR(64) DEFAULT NULL COMMENT 'query-execution 内的运行时改写绑定标识符' AFTER publish_status,
  ADD COLUMN runtime_binding_at DATETIME DEFAULT NULL COMMENT '运行时绑定时间戳' AFTER runtime_binding_id,
  ADD COLUMN runtime_binding_by VARCHAR(64) DEFAULT NULL COMMENT '运行时绑定操作人标识符' AFTER runtime_binding_at,
  ADD COLUMN runtime_binding_scope VARCHAR(128) DEFAULT NULL COMMENT '运行时绑定范围，例如租户和 SQL 指纹' AFTER runtime_binding_by,
  ADD COLUMN published_sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '发布到运行时绑定的 SQL 指纹' AFTER runtime_binding_scope,
  ADD COLUMN runtime_rule_version VARCHAR(64) DEFAULT NULL COMMENT 'query-execution 返回的运行时改写规则版本' AFTER published_sql_fingerprint,
  ADD KEY idx_rewrite_record_review (tenant_id, review_status, created_at),
  ADD KEY idx_rewrite_record_publish (tenant_id, publish_status, updated_at),
  ADD KEY idx_rewrite_record_runtime_binding (tenant_id, runtime_binding_id);
