ALTER TABLE acceleration_recommendation
  ADD COLUMN source_type VARCHAR(32) DEFAULT NULL COMMENT 'PARSE/QUERY source type for recommendation traceability' AFTER status,
  ADD COLUMN source_kind VARCHAR(64) DEFAULT NULL COMMENT 'Governance source kind such as STRUCTURE_PARSE/QUERY_HISTORY' AFTER source_type,
  ADD COLUMN source_id VARCHAR(128) DEFAULT NULL COMMENT 'Canonical source identifier paired with source type/kind' AFTER source_kind,
  ADD COLUMN evidence_level VARCHAR(32) DEFAULT NULL COMMENT 'STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED' AFTER source_id,
  ADD COLUMN schema_version VARCHAR(64) NOT NULL DEFAULT 'SQL_RECOMMENDATION_RULE_MODEL_V1' COMMENT 'Recommendation rule output schema version' AFTER evidence_level,
  ADD COLUMN rule_chain_json JSON DEFAULT NULL COMMENT 'Applied or selected recommendation rule chain evidence' AFTER schema_version,
  ADD COLUMN unapplied_rules_json JSON DEFAULT NULL COMMENT 'Rules considered but not applied with reason evidence' AFTER rule_chain_json,
  ADD COLUMN preconditions_json JSON DEFAULT NULL COMMENT 'Preconditions required before validation or later apply' AFTER unapplied_rules_json,
  ADD COLUMN semantic_risks_json JSON DEFAULT NULL COMMENT 'Semantic risks that require validation or manual review' AFTER preconditions_json,
  ADD COLUMN expected_benefit_json JSON DEFAULT NULL COMMENT 'Static estimated benefit evidence, not real execution gain' AFTER semantic_risks_json,
  ADD COLUMN estimated_cost_json JSON DEFAULT NULL COMMENT 'Static estimated cost and governance follow-up evidence' AFTER expected_benefit_json,
  ADD COLUMN confidence INT DEFAULT NULL COMMENT 'Static model confidence score 0-100' AFTER estimated_cost_json,
  ADD COLUMN validation_method VARCHAR(64) DEFAULT NULL COMMENT 'Required validation method before approval or later apply' AFTER confidence,
  ADD COLUMN validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT 'NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED' AFTER validation_method,
  ADD COLUMN auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether later automatic apply is allowed after validation' AFTER validation_status,
  ADD COLUMN manual_review_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether recommendation requires manual review' AFTER auto_apply_allowed,
  ADD KEY idx_acc_reco_source (tenant_id, source_type, source_kind, source_id),
  ADD KEY idx_acc_reco_validation (tenant_id, validation_status, manual_review_required);
