CREATE TABLE IF NOT EXISTS runtime_rewrite_binding (
  runtime_binding_id VARCHAR(64) NOT NULL COMMENT 'query-execution 持有的运行时改写绑定标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT '已发布 sql_rewrite_record 标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联推荐标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '改写来源类型，例如 PARSE 或 QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '改写来源种类',
  source_id VARCHAR(128) NOT NULL COMMENT '改写来源对象标识符',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '用于运行时查找的原始 SQL 指纹',
  original_sql_digest VARCHAR(128) NOT NULL COMMENT '原始 SQL 摘要或摘要哈希',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '该绑定生效时要应用的已批准 SQL 文本',
  datasource_code VARCHAR(128) NOT NULL COMMENT '运行时数据源或方言证据',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '运行时改写绑定状态：ACTIVE/PAUSED/UNPUBLISHED',
  rule_version BIGINT NOT NULL DEFAULT 1 COMMENT '每租户与 SQL 指纹单调递增的运行时规则版本',
  runtime_rule_version VARCHAR(64) NOT NULL COMMENT '返回给 sql-optimization 的外部运行时规则版本',
  published_by VARCHAR(64) NOT NULL COMMENT '发布操作人或服务主体',
  published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间戳',
  paused_by VARCHAR(64) DEFAULT NULL COMMENT '暂停操作人或服务主体',
  paused_at DATETIME DEFAULT NULL COMMENT '暂停时间戳',
  pause_reason VARCHAR(512) DEFAULT NULL COMMENT '暂停原因',
  unpublished_by VARCHAR(64) DEFAULT NULL COMMENT '下线操作人或服务主体',
  unpublished_at DATETIME DEFAULT NULL COMMENT '下线时间戳',
  unpublish_reason VARCHAR(512) DEFAULT NULL COMMENT '下线原因',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  active_binding_key VARCHAR(320) GENERATED ALWAYS AS (
    CASE WHEN status = 'ACTIVE' THEN CONCAT(tenant_id, '::', sql_fingerprint) ELSE NULL END
  ) STORED,
  PRIMARY KEY (runtime_binding_id),
  UNIQUE KEY uk_runtime_rewrite_active_binding (active_binding_key),
  KEY idx_runtime_rewrite_tenant_fingerprint (tenant_id, sql_fingerprint, status),
  KEY idx_runtime_rewrite_record (tenant_id, rewrite_record_id),
  KEY idx_runtime_rewrite_version (tenant_id, sql_fingerprint, rule_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Query-execution production runtime SQL rewrite binding truth';
