CREATE TABLE IF NOT EXISTS acceleration_recommendation (
  recommendation_id VARCHAR(64) NOT NULL COMMENT 'Recommendation identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  recommendation_type VARCHAR(32) NOT NULL COMMENT 'REWRITE/ACCELERATION/CREATE_TABLE/PREWARM/MAINTENANCE',
  source_sql_id VARCHAR(64) DEFAULT NULL COMMENT 'Source SQL, parse item, history, or task identifier',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT 'Normalized SQL fingerprint',
  source_sql_text MEDIUMTEXT DEFAULT NULL COMMENT 'Original SQL text or template',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT 'Recommended SQL, create table SQL, prewarm SQL, or maintenance SQL',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT 'Target execution engine',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT 'Target datasource code',
  report_code VARCHAR(128) DEFAULT NULL COMMENT 'Related report code',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT 'Related logical object key',
  summary VARCHAR(512) DEFAULT NULL COMMENT 'Recommendation summary',
  reason TEXT DEFAULT NULL COMMENT 'Recommendation reason',
  expected_gain VARCHAR(512) DEFAULT NULL COMMENT 'Expected benefit description',
  benefit_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'UNKNOWN/LOW/MEDIUM/HIGH',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'UNKNOWN/LOW/MEDIUM/HIGH/CRITICAL',
  risk_summary TEXT DEFAULT NULL COMMENT 'Risk summary and constraints',
  requires_dispatch TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 if external loading/dispatch coordination is required',
  status VARCHAR(32) NOT NULL DEFAULT 'RECOMMENDED' COMMENT 'RECOMMENDED/REVIEWING/DISPATCH_READY/CANCELLED; no executed state in SQLForge',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Recommendation creator',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (recommendation_id),
  KEY idx_acc_reco_tenant_type_created (tenant_id, recommendation_type, created_at),
  KEY idx_acc_reco_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_reco_sql_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_reco_report_code (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Read-only SQL acceleration and rewrite recommendation catalog';
