CREATE TABLE IF NOT EXISTS metadata_column_snapshot (
  column_snapshot_id VARCHAR(64) NOT NULL COMMENT '字段级元数据快照标识符',
  snapshot_id VARCHAR(64) NOT NULL COMMENT '关联 metadata_snapshot 标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码',
  object_type VARCHAR(32) NOT NULL COMMENT '对象类型：DB_VIEW/TABLE/LOGICAL_VIEW 等',
  object_key VARCHAR(255) NOT NULL COMMENT '规范对象键',
  column_name VARCHAR(255) NOT NULL COMMENT '字段名称',
  column_ordinal INT DEFAULT NULL COMMENT '字段序号',
  data_type VARCHAR(128) DEFAULT NULL COMMENT '字段类型',
  nullable_flag TINYINT(1) DEFAULT NULL COMMENT '是否可空',
  primary_key_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主键或唯一键证据',
  partition_key_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否分区字段证据',
  expression_text TEXT DEFAULT NULL COMMENT '视图字段表达式或派生字段定义',
  source_column_refs_json JSON DEFAULT NULL COMMENT '展开后的来源字段引用快照',
  evidence_source VARCHAR(64) DEFAULT NULL COMMENT '证据来源',
  snapshot_time DATETIME DEFAULT NULL COMMENT '字段快照采集时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (column_snapshot_id),
  UNIQUE KEY uk_metadata_column_snapshot_object_column (tenant_id, object_key, column_name),
  KEY idx_metadata_column_snapshot_parent (tenant_id, snapshot_id),
  KEY idx_metadata_column_snapshot_object (tenant_id, object_key, column_ordinal),
  KEY idx_metadata_column_snapshot_datasource_time (tenant_id, datasource_code, snapshot_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance field-level metadata snapshot catalog';
