CREATE TABLE IF NOT EXISTS datasource_config (
  datasource_id VARCHAR(64) NOT NULL COMMENT '数据源配置标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) NOT NULL COMMENT '数据源业务编码',
  datasource_name VARCHAR(128) DEFAULT NULL COMMENT '数据源显示名称',
  engine_type VARCHAR(32) NOT NULL DEFAULT 'HETU' COMMENT '执行引擎类型，例如 HETU/HIVE/SPARK',
  connection_mode VARCHAR(32) NOT NULL COMMENT '连接模式：JDBC/API/REST/CLIENT/GATEWAY/PROXY',
  stage VARCHAR(32) NOT NULL DEFAULT 'PROD' COMMENT '环境阶段',
  jdbc_url VARCHAR(1024) DEFAULT NULL COMMENT 'JDBC 连接 URL',
  jdbc_driver_class_name VARCHAR(255) DEFAULT NULL COMMENT 'JDBC 驱动类名',
  username VARCHAR(255) DEFAULT NULL COMMENT '数据源用户名',
  api_base_url VARCHAR(512) DEFAULT NULL COMMENT 'API 基础 URL',
  client_endpoint VARCHAR(512) DEFAULT NULL COMMENT '客户端端点',
  gateway_endpoint VARCHAR(512) DEFAULT NULL COMMENT '网关端点',
  proxy_endpoint VARCHAR(512) DEFAULT NULL COMMENT '代理端点',
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '认证模式',
  credential_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '凭据模式',
  credential_ref VARCHAR(255) DEFAULT NULL COMMENT '外部凭据引用',
  credential_mask VARCHAR(128) DEFAULT NULL COMMENT '凭据脱敏预览',
  credential_ciphertext TEXT DEFAULT NULL COMMENT 'AES-256 加密的凭据密文',
  encryption_algorithm VARCHAR(32) DEFAULT NULL COMMENT '凭据加密算法',
  encryption_key_id VARCHAR(64) DEFAULT NULL COMMENT '凭据加密密钥标识符',
  tls_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'TLS 启用标志',
  verify_peer TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'TLS 对端校验标志',
  readonly_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT '只读数据源边界',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用标志',
  timeout_ms INT NOT NULL DEFAULT 3000 COMMENT '连接超时时间，单位毫秒',
  health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '最近健康状态',
  last_failure_reason VARCHAR(255) DEFAULT NULL COMMENT '最近健康检查失败原因',
  last_checked_at DATETIME DEFAULT NULL COMMENT '最近健康检查时间戳',
  last_check_elapsed_ms BIGINT DEFAULT NULL COMMENT '最近健康检查耗时毫秒数',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (datasource_id),
  UNIQUE KEY uk_datasource_config_tenant_code_engine (tenant_id, datasource_code, engine_type),
  KEY idx_datasource_config_tenant (tenant_id, update_time),
  KEY idx_datasource_config_health (tenant_id, health_status, last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance datasource connection configuration';
