CREATE TABLE IF NOT EXISTS acceleration_candidate (
  candidate_id VARCHAR(64) NOT NULL COMMENT '加速候选标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '来源族：PARSE/QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '归一化来源类型',
  source_id VARCHAR(128) NOT NULL COMMENT '来源对象标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT '关联sql_parse_历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse task标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse/报表批次标识符',
  batch_item_id VARCHAR(64) DEFAULT NULL COMMENT '关联解析/报表批次条目标识符',
  benchmark_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联压测 task标识符',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联optimization task标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '关联数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '来源环境或生命周期阶段',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  candidate_type VARCHAR(32) NOT NULL DEFAULT 'ACCELERATION_AND_REWRITE' COMMENT '候选类型：ACCELERATION/REWRITE/ACCELERATION_AND_REWRITE',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '候选状态：DRAFT/RECOMMENDED/PLAN_CREATED/REJECTED/INVALID/CANCELLED',
  confidence DECIMAL(5,4) DEFAULT NULL COMMENT '静态置信分，非运行时收益证明',
  priority INT DEFAULT NULL COMMENT '操作人排序用候选优先级',
  evidence_level VARCHAR(32) NOT NULL COMMENT '证据level：STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED',
  schema_version VARCHAR(32) DEFAULT NULL COMMENT '候选载荷模式版本',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '候选创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  source_evidence_json JSON DEFAULT NULL COMMENT '归一化来源证据',
  issue_evidence_json JSON DEFAULT NULL COMMENT '静态解析问题证据',
  runtime_evidence_json JSON DEFAULT NULL COMMENT '仅运行时证据摘要',
  benefit_estimate_json JSON DEFAULT NULL COMMENT '预估收益证据，非真实收益证明',
  cost_estimate_json JSON DEFAULT NULL COMMENT '预估实现或校验成本',
  risk_json JSON DEFAULT NULL COMMENT '风险证据与人工评审提示',
  PRIMARY KEY (candidate_id),
  KEY idx_acc_candidate_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_candidate_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_acc_candidate_history (tenant_id, history_id),
  KEY idx_acc_candidate_parse_history (tenant_id, parse_history_id),
  KEY idx_acc_candidate_optimization_task (tenant_id, optimization_task_id),
  KEY idx_acc_candidate_benchmark_task (tenant_id, benchmark_task_id),
  KEY idx_acc_candidate_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_candidate_report (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed acceleration and rewrite candidate persistence';

CREATE TABLE IF NOT EXISTS sql_rewrite_record (
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT 'SQL 改写记录标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联加速推荐标识符',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联optimization task标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '来源族：PARSE/QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '归一化来源类型',
  source_id VARCHAR(128) NOT NULL COMMENT '来源对象标识符',
  evidence_level VARCHAR(32) NOT NULL COMMENT '改写来源证据级别',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT '关联sql_parse_历史标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '关联数据源编码',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '改写状态：DRAFT/RECOMMENDED/APPROVED/APPLIED/PAUSED/ROLLED_BACK/DEPRECATED/CANCELLED',
  validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT '校验状态：NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示治理允许自动应用',
  manual_review_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示应用前需要人工评审',
  validation_policy_id VARCHAR(64) DEFAULT NULL COMMENT '校验策略标识符',
  last_validation_run_id VARCHAR(64) DEFAULT NULL COMMENT '最近一次校验运行标识符',
  last_compared_at DATETIME DEFAULT NULL COMMENT '最近一次对比时间戳',
  alert_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '告警状态：NONE/OPEN/ACKED/RESOLVED/SUPPRESSED',
  original_sql_text MEDIUMTEXT NOT NULL COMMENT '用于治理差异对比和追踪的原始 SQL 文本',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '用于治理差异对比和追踪的推荐 SQL 文本',
  executed_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '存在受治理应用路径时的已执行 SQL 文本',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '记录创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  rule_chain_json JSON DEFAULT NULL COMMENT '已应用改写规则链证据',
  diff_summary_json JSON DEFAULT NULL COMMENT '差异摘要证据',
  risk_json JSON DEFAULT NULL COMMENT '风险与评审证据',
  trace_refs_json JSON DEFAULT NULL COMMENT '跨服务追踪引用',
  PRIMARY KEY (rewrite_record_id),
  KEY idx_rewrite_record_tenant_status_created (tenant_id, status, created_at),
  KEY idx_rewrite_record_validation (tenant_id, validation_status, last_compared_at),
  KEY idx_rewrite_record_recommendation (tenant_id, recommendation_id),
  KEY idx_rewrite_record_optimization_task (tenant_id, optimization_task_id),
  KEY idx_rewrite_record_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_rewrite_record_history (tenant_id, history_id),
  KEY idx_rewrite_record_parse_history (tenant_id, parse_history_id),
  KEY idx_rewrite_record_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_rewrite_record_last_run (tenant_id, last_validation_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite record persistence';

CREATE TABLE IF NOT EXISTS rewrite_validation_run (
  validation_run_id VARCHAR(64) NOT NULL COMMENT '改写校验运行标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT '引用的改写记录标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联加速推荐标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '运行状态：PENDING/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  comparison_status VARCHAR(32) NOT NULL DEFAULT 'NOT_COMPARED' COMMENT '对比状态：NOT_COMPARED/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  difference_type VARCHAR(64) NOT NULL DEFAULT 'NONE' COMMENT '差异类型：NONE/SCHEMA_DIFF/ROW_COUNT_DIFF/KEY_SET_DIFF/ORDER_DIFF/VALUE_DIFF/CHECKSUM_DIFF/TIMEZONE_OR_PRECISION_DIFF/UNKNOWN',
  auto_apply_paused TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示校验已暂停自动应用',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '校验开始时间戳',
  finished_at DATETIME DEFAULT NULL COMMENT '校验结束时间戳',
  comparison_policy_json JSON DEFAULT NULL COMMENT '校验策略快照',
  original_result_digest_json JSON DEFAULT NULL COMMENT '原始 SQL 结果摘要，非完整结果集',
  recommended_result_digest_json JSON DEFAULT NULL COMMENT '推荐 SQL 结果摘要，非完整结果集',
  difference_sample_json JSON DEFAULT NULL COMMENT '有限差异样本证据',
  execution_evidence_json JSON DEFAULT NULL COMMENT '只读执行或压测证据摘要',
  PRIMARY KEY (validation_run_id),
  KEY idx_validation_run_rewrite_started (tenant_id, rewrite_record_id, started_at),
  KEY idx_validation_run_recommendation (tenant_id, recommendation_id),
  KEY idx_validation_run_history (tenant_id, history_id),
  KEY idx_validation_run_status_started (tenant_id, status, started_at),
  KEY idx_validation_run_comparison (tenant_id, comparison_status, difference_type),
  KEY idx_validation_run_fingerprint (tenant_id, sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite validation run persistence';
