CREATE TABLE IF NOT EXISTS datasource_config (
  datasource_id VARCHAR(64) NOT NULL COMMENT 'Datasource config identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  datasource_code VARCHAR(128) NOT NULL COMMENT 'Datasource business code',
  datasource_name VARCHAR(128) DEFAULT NULL COMMENT 'Datasource display name',
  engine_type VARCHAR(32) NOT NULL DEFAULT 'HETU' COMMENT 'Execution engine type such as HETU/HIVE/SPARK',
  connection_mode VARCHAR(32) NOT NULL COMMENT 'JDBC/API/REST/CLIENT/GATEWAY/PROXY',
  stage VARCHAR(32) NOT NULL DEFAULT 'PROD' COMMENT 'Environment stage',
  jdbc_url VARCHAR(1024) DEFAULT NULL COMMENT 'JDBC connection URL',
  jdbc_driver_class_name VARCHAR(255) DEFAULT NULL COMMENT 'JDBC driver class name',
  username VARCHAR(255) DEFAULT NULL COMMENT 'Datasource username',
  api_base_url VARCHAR(512) DEFAULT NULL COMMENT 'API base URL',
  client_endpoint VARCHAR(512) DEFAULT NULL COMMENT 'Client endpoint',
  gateway_endpoint VARCHAR(512) DEFAULT NULL COMMENT 'Gateway endpoint',
  proxy_endpoint VARCHAR(512) DEFAULT NULL COMMENT 'Proxy endpoint',
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'Authentication mode',
  credential_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'Credential mode',
  credential_ref VARCHAR(255) DEFAULT NULL COMMENT 'External credential reference',
  credential_mask VARCHAR(128) DEFAULT NULL COMMENT 'Masked credential preview',
  credential_ciphertext TEXT DEFAULT NULL COMMENT 'AES-256 encrypted credential secret',
  encryption_algorithm VARCHAR(32) DEFAULT NULL COMMENT 'Credential encryption algorithm',
  encryption_key_id VARCHAR(64) DEFAULT NULL COMMENT 'Credential encryption key identifier',
  tls_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'TLS enabled flag',
  verify_peer TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'TLS peer verification flag',
  readonly_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Readonly datasource boundary',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Enabled flag',
  timeout_ms INT NOT NULL DEFAULT 3000 COMMENT 'Connection timeout in milliseconds',
  health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'Last health status',
  last_failure_reason VARCHAR(255) DEFAULT NULL COMMENT 'Last health-check failure reason',
  last_checked_at DATETIME DEFAULT NULL COMMENT 'Last health-check timestamp',
  last_check_elapsed_ms BIGINT DEFAULT NULL COMMENT 'Last health-check elapsed milliseconds',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (datasource_id),
  UNIQUE KEY uk_datasource_config_tenant_code_engine (tenant_id, datasource_code, engine_type),
  KEY idx_datasource_config_tenant (tenant_id, update_time),
  KEY idx_datasource_config_health (tenant_id, health_status, last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance datasource connection configuration';
