CREATE TABLE IF NOT EXISTS parse_batch (
  batch_id VARCHAR(64) NOT NULL COMMENT '解析批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  batch_name VARCHAR(255) NOT NULL COMMENT '批次显示名称',
  import_mode VARCHAR(32) NOT NULL COMMENT '导入模式，例如 SQL_FILE/TABULAR_FILE/REPORT_CATALOG',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型，例如 FILE_UPLOAD/REPORT_CATALOG_IMPORT',
  file_type VARCHAR(16) NOT NULL COMMENT '上传文件类型',
  template_version VARCHAR(32) DEFAULT NULL COMMENT '模板版本',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码覆盖值',
  structure_parse_only TINYINT(1) NOT NULL DEFAULT 0 COMMENT '批次是否仅运行结构解析',
  status VARCHAR(32) NOT NULL COMMENT '当前批次状态',
  total_records INT NOT NULL DEFAULT 0 COMMENT '导入记录数',
  success_records INT NOT NULL DEFAULT 0 COMMENT '成功记录数',
  partial_success_records INT NOT NULL DEFAULT 0 COMMENT '部分成功记录数',
  failed_records INT NOT NULL DEFAULT 0 COMMENT '失败记录数',
  structure_parse_success_rate DECIMAL(6,2) DEFAULT NULL COMMENT '结构解析成功率百分比',
  access_parse_success_rate DECIMAL(6,2) DEFAULT NULL COMMENT '访问解析成功率百分比',
  status_history_json JSON NOT NULL COMMENT '批次状态历史载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '批次创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id),
  KEY idx_parse_batch_tenant_status_created (tenant_id, status, created_at),
  KEY idx_parse_batch_tenant_mode (tenant_id, import_mode, file_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bulk parse batch contract baseline';
