CREATE TABLE IF NOT EXISTS optimization_task (
  task_id VARCHAR(64) NOT NULL COMMENT 'Optimization task identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Tenant identifier',
  task_type VARCHAR(32) NOT NULL COMMENT 'Optimization task type: PARSE/REWRITE/ACCELERATION_SUGGESTION',
  sql_text LONGTEXT DEFAULT NULL COMMENT 'Submitted SQL text snapshot',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT 'Normalized SQL fingerprint',
  datasource_type VARCHAR(32) NOT NULL COMMENT 'Datasource type',
  priority VARCHAR(16) NOT NULL COMMENT 'Task priority',
  parse_depth VARCHAR(16) NOT NULL COMMENT 'Parse depth',
  callback_url VARCHAR(2048) DEFAULT NULL COMMENT 'Optional callback URL',
  requested_suggestion_types_json JSON DEFAULT NULL COMMENT 'Requested acceleration suggestion types JSON',
  status VARCHAR(16) NOT NULL COMMENT 'Task status: QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  current_phase VARCHAR(32) NOT NULL COMMENT 'Current task phase',
  progress_percent INT NOT NULL DEFAULT 0 COMMENT 'Progress percentage',
  summary TEXT DEFAULT NULL COMMENT 'Task summary when completed',
  error_code INT DEFAULT NULL COMMENT 'Failure code',
  error_message VARCHAR(512) DEFAULT NULL COMMENT 'Desensitized failure message',
  error_suggested_action VARCHAR(512) DEFAULT NULL COMMENT 'Suggested follow-up action',
  error_retryable TINYINT(1) DEFAULT NULL COMMENT 'Whether failure is retryable',
  status_history_json JSON NOT NULL COMMENT 'Ordered status transition history JSON',
  submitted_at DATETIME(3) NOT NULL COMMENT 'Submit timestamp',
  started_at DATETIME(3) DEFAULT NULL COMMENT 'Worker start timestamp',
  finished_at DATETIME(3) DEFAULT NULL COMMENT 'Finish timestamp',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (task_id),
  KEY idx_optimization_task_status_submitted (status, submitted_at),
  KEY idx_optimization_task_tenant_time (tenant_id, create_time),
  KEY idx_optimization_task_fingerprint (sql_fingerprint)
);
