CREATE TABLE IF NOT EXISTS dispatch_event (
  dispatch_event_id VARCHAR(64) NOT NULL COMMENT '分发事件标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_id VARCHAR(64) NOT NULL COMMENT '来源推荐标识符',
  dispatch_type VARCHAR(32) NOT NULL COMMENT '分发类型：REWRITE_SQL/ACCELERATION_SQL/CREATE_TABLE_SQL/PREWARM_SQL/MAINTENANCE_SQL',
  dispatch_payload_json JSON NOT NULL COMMENT '面向外部装载或维护模块的拉取式分发载荷',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '目标执行引擎',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT '目标数据源编码',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  status VARCHAR(32) NOT NULL COMMENT '分发状态：CREATED/PUBLISHED/PULLED/ACKED/FAILED',
  pulled_by VARCHAR(64) DEFAULT NULL COMMENT '拉取事件的外部模块或操作人',
  pulled_at DATETIME DEFAULT NULL COMMENT '拉取时间戳',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT '确认事件的外部模块或操作人',
  acked_at DATETIME DEFAULT NULL COMMENT '确认时间戳',
  failed_by VARCHAR(64) DEFAULT NULL COMMENT '标记事件失败的外部模块或操作人',
  failed_at DATETIME DEFAULT NULL COMMENT '失败时间戳',
  result_message TEXT DEFAULT NULL COMMENT '外部模块返回的确认/失败消息',
  status_history_json JSON NOT NULL COMMENT '仅追加状态流转证据',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '分发创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (dispatch_event_id),
  KEY idx_dispatch_event_tenant_status_created (tenant_id, status, created_at),
  KEY idx_dispatch_event_recommendation (tenant_id, recommendation_id),
  KEY idx_dispatch_event_report_code (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pull-based recommendation dispatch state machine';
