CREATE TABLE IF NOT EXISTS report_batch (
  batch_id VARCHAR(64) NOT NULL COMMENT 'Report catalog batch identifier',
  tenant_id VARCHAR(64) NOT NULL COMMENT 'Owning tenant identifier',
  batch_name VARCHAR(255) NOT NULL COMMENT 'Batch display name',
  file_type VARCHAR(16) NOT NULL COMMENT 'Source file type, currently TXT for mock source',
  report_code_field VARCHAR(128) NOT NULL COMMENT 'Column name that contains report_code',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT 'Datasource code override',
  stage VARCHAR(32) DEFAULT NULL COMMENT 'Stage metadata such as DEV/UAT/PROD',
  priority VARCHAR(32) DEFAULT NULL COMMENT 'Priority hint',
  source_type VARCHAR(32) NOT NULL COMMENT 'Source type such as TXT_MOCK_SOURCE',
  status VARCHAR(32) NOT NULL COMMENT 'Current batch status',
  total_reports INT NOT NULL DEFAULT 0 COMMENT 'Imported report count',
  resolved_reports INT NOT NULL DEFAULT 0 COMMENT 'Resolved report count',
  failed_reports INT NOT NULL DEFAULT 0 COMMENT 'Failed report count',
  status_history_json JSON NOT NULL COMMENT 'Batch status history payload',
  created_by VARCHAR(64) DEFAULT NULL COMMENT 'Batch creator',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (batch_id),
  KEY idx_report_batch_tenant_status_created (tenant_id, status, created_at),
  KEY idx_report_batch_tenant_code (tenant_id, report_code_field)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog batch baseline';

CREATE TABLE IF NOT EXISTS report_batch_item (
  item_id VARCHAR(64) NOT NULL COMMENT 'Report batch item identifier',
  batch_id VARCHAR(64) NOT NULL COMMENT 'Owning report batch identifier',
  sequence_number INT NOT NULL COMMENT '1-based sequence number inside the uploaded batch',
  report_code VARCHAR(128) NOT NULL COMMENT 'Report code',
  report_name VARCHAR(255) DEFAULT NULL COMMENT 'Report name',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT 'Datasource code resolved for this row',
  stage VARCHAR(32) DEFAULT NULL COMMENT 'Stage metadata',
  priority VARCHAR(32) DEFAULT NULL COMMENT 'Priority hint',
  source_file_line VARCHAR(512) DEFAULT NULL COMMENT 'Original source line or CSV payload summary',
  sql_column_name VARCHAR(128) DEFAULT NULL COMMENT 'Source spreadsheet column that supplied this SQL',
  sql_ordinal_in_report INT DEFAULT NULL COMMENT '1-based SQL ordinal inside the same report_code',
  sql_text MEDIUMTEXT DEFAULT NULL COMMENT 'Resolved SQL text',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT 'Parse task identifier',
  structure_syntax_status VARCHAR(32) DEFAULT NULL COMMENT 'Structure parse syntax status',
  access_service_status VARCHAR(32) DEFAULT NULL COMMENT 'Access parse provider status',
  access_connection_status VARCHAR(32) DEFAULT NULL COMMENT 'Access parse connection status',
  failure_reason VARCHAR(128) DEFAULT NULL COMMENT 'Failure or degrade reason',
  status VARCHAR(32) NOT NULL COMMENT 'Current item status',
  issue_scenes_json JSON DEFAULT NULL COMMENT 'Issue scene summary payload',
  logical_object_keys_json JSON DEFAULT NULL COMMENT 'Logical object hit summary payload',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation timestamp',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last update timestamp',
  PRIMARY KEY (item_id),
  KEY idx_report_batch_item_batch_seq (batch_id, sequence_number),
  KEY idx_report_batch_item_batch_status (batch_id, status),
  KEY idx_report_batch_item_report (batch_id, report_code),
  KEY idx_report_batch_item_report_sql (batch_id, report_code, sql_ordinal_in_report)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog imported records and parse evidence';
