-- fixture_id=test01_wrapper_count_05
-- fixture_category=test01_variant
-- nested_layers=10
SELECT COUNT(*) AS row_count FROM (
-- YH_QUERYID=1d516d3b74da409a9f2a5ed3873e5c7e
-- YH_RPTID=SZ_0000003772
-- YH_RPTINSTID=百万客户净增报表20260521154649-1556
-- YH_RPTORG=41H006
-- YH_RPTVIEWUSER=user_4a7d873e0c8d404d839494be151bd70a_850001953VIEW
-- YH_RPTVIEWROLELIST=everyone_role
-- YH_RPTVIEWMODE=PUBLISH
-- YH_SQLSENDTIME=2026-05-21 15:51:40
-- YH_RPTWIDGETTYPE=Table
-- YH_RPTWIDGETNAME=图表1
-- YH_REFDATASET=万象发布管理WXFBGL/SZ_0000003772_20260518100302_a09c1d1217954c88bffc19c00738901/个金/百万客户净增报表
-- YH_DATE_CC=FALSE
-- YH_RPTSEARCHMODE=HETU
SELECT "Sub44_分组和汇总10_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub44_分组和汇总10_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub44_分组和汇总10_BASE"."org" AS "org", 
"Sub44_分组和汇总10_BASE"."基期100" AS "基期100", 
"Sub44_分组和汇总10_BASE"."当期100" AS "当期100", 
"Sub44_分组和汇总10_BASE"."新增100" AS "新增100",
"Sub44_分组和汇总10_BASE"."新增100-600" AS "新增100-600", 
SUM("Sub44_分组和汇总10_BASE"."当期100" - "Sub44_分组和汇总10_BASE"."基期100") AS "Sum_增量100", 
SUM((CASE CAST("Sub44_分组和汇总10_BASE"."当期100" - "Sub44_分组和汇总10_BASE"."基期100" AS VARCHAR(255))
WHEN '' THEN NULL
ELSE CAST(CAST("Sub44_分组和汇总10_BASE"."当期100" - "Sub44_分组和汇总10_BASE"."基期100" AS VARCHAR(255)) AS double)
END) / CASE CAST("Sub44_分组和汇总10_BASE"."基期100" AS VARCHAR(255))
WHEN '' THEN NULL
ELSE CAST(CAST("Sub44_分组和汇总10_BASE"."基期100" AS VARCHAR(255)) AS double)
END) AS "Sum_增速100", 
SUM("Sub44_分组和汇总10_BASE"."当期100-600" - "Sub44_分组和汇总10_BASE"."基期100-600") AS "Sum_增量100-600", 
SUM((CASE CAST("Sub44_分组和汇总10_BASE"."当期100-600" - "Sub44_分组和汇总10_BASE"."基期100-600" AS VARCHAR(255))
WHEN '' THEN NULL
ELSE CAST(CAST("Sub44_分组和汇总10_BASE"."当期100-600" - "Sub44_分组和汇总10_BASE"."基期100-600" AS VARCHAR(255)) AS double)
END) / CASE CAST("Sub44_分组和汇总10_BASE"."基期100-600" AS VARCHAR(255))
WHEN '' THEN NULL
ELSE CAST(CAST("Sub44_分组和汇总10_BASE"."基期100-600" AS VARCHAR(255)) AS double)
END) AS "Sum_增速100-600",
SUM("Sub44_分组和汇总10_BASE"."当期600" - "Sub44_分组和汇总10_BASE"."基期600") AS "Sum_增量600"
FROM (
SELECT "Sub34_分组和汇总4"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub34_分组和汇总4"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub34_分组和汇总4"."org" AS "org", 
"Sub34_分组和汇总4"."DistinctCount_客户编号" AS "基期100", 
"Sub35_分组和汇总5"."DistinctCount_客户编号" AS "基期100-600",
"Sub36_分组和汇总6"."DistinctCount_客户编号" AS "基期600", 
"Sub37_分组和汇总7"."DistinctCount_客户编号" AS "当期100", 
"Sub39_分组和汇总9"."DistinctCount_客户编号" AS "当期600", 
"Sub38_分组和汇总8"."DistinctCount_客户编号" AS "当期100-600", 
"Sub40_分组和汇总11"."DistinctCount_客户编号" AS "新增100",
"Sub41_分组和汇总12"."DistinctCount_客户编号" AS "新增100-600"
FROM (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260430'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 1000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号", "Sub9_分组和汇总1"."机构编码__第二层机构简称", "Sub9_分组和汇总1"."org") "Sub34_分组和汇总4"
)
LEFT JOIN (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260430'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 1000000
AND "Sub9_分组和汇总1"."Sum_月日均AUM" < 6000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号") "Sub35_分组和汇总5"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub35_分组和汇总5"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260430'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 6000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号") "Sub36_分组和汇总6"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub36_分组和汇总6"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260519'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 1000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号", "Sub9_分组和汇总1"."机构编码__第二层机构简称", "Sub9_分组和汇总1"."org") "Sub37_分组和汇总7"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub37_分组和汇总7"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260519'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 1000000
AND "Sub9_分组和汇总1"."Sum_月日均AUM" < 6000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号") "Sub38_分组和汇总8"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub38_分组和汇总8"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub9_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub9_分组和汇总1"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub9_分组和汇总1"."org" AS "org", 
COUNT(DISTINCT "Sub9_分组和汇总1"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub6_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub6_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub6_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub6_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub6_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY "Sub3_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub3_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub6_分组和汇总1_BASE"
UNION ALL
SELECT "Sub8_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub8_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub8_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub8_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub8_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub3_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub3_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub3_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub3_分组和汇总_BASE"
GROUP BY CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub3_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub3_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub3_分组和汇总_BASE"."客户编号", 
"Sub3_分组和汇总_BASE"."数据日期"
) "Sub8_分组和汇总2_BASE"
) "Sub9_分组和汇总1"
WHERE "Sub9_分组和汇总1"."数据日期" = '20260519'
AND "Sub9_分组和汇总1"."Sum_月日均AUM" >= 6000000
GROUP BY "Sub9_分组和汇总1"."机构编码__第二层时点机构号") "Sub39_分组和汇总9"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub39_分组和汇总9"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub31_分组和汇总3"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
COUNT(DISTINCT "Sub31_分组和汇总3"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub27_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub27_分组和汇总1"."客户编号" AS "客户编号"
, SUM(CASE WHEN "Sub27_分组和汇总1"."数据日期" = '20260430' THEN "Sub27_分组和汇总1"."Sum_月日均AUM" ELSE 0 END) AS "Sum_基期AUM"
, SUM(CASE WHEN "Sub27_分组和汇总1"."数据日期" = '20260519' THEN "Sub27_分组和汇总1"."Sum_月日均AUM" ELSE 0 END) AS "Sum_当期AUM"
FROM (
SELECT "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."客户编号" AS "客户编号",
SUM(CASE WHEN "Sub24_分组和汇总1_BASE"."数据日期" = '20260430' THEN "Sub24_分组和汇总1_BASE"."Sum_月日均AUM" ELSE 0 END) AS "Sum_基期AUM",
SUM(CASE WHEN "Sub24_分组和汇总1_BASE"."数据日期" = '20260519' THEN "Sub24_分组和汇总1_BASE"."Sum_月日均AUM" ELSE 0 END) AS "Sum_当期AUM"
FROM (
SELECT "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub24_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub24_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub24_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub21_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub21_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub21_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub21_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub21_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub21_分组和汇总_BASE"
GROUP BY "Sub21_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub21_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub21_分组和汇总_BASE"."客户编号", 
"Sub21_分组和汇总_BASE"."数据日期"
) "Sub24_分组和汇总1_BASE"
UNION ALL
SELECT "Sub26_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub26_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub26_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub26_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub26_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub26_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub21_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub21_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub21_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub21_分组和汇总_BASE"
GROUP BY CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub21_分组和汇总_BASE"."客户编号", 
"Sub21_分组和汇总_BASE"."数据日期"
) "Sub26_分组和汇总2_BASE"
) "Sub24_分组和汇总1_BASE"
GROUP BY "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."客户编号"
) "Sub27_分组和汇总1"
GROUP BY "Sub27_分组和汇总1"."机构编码__第二层时点机构号", 
"Sub27_分组和汇总1"."客户编号"
) "Sub31_分组和汇总3"
WHERE "Sub31_分组和汇总3"."Sum_基期AUM" < 1000000
AND "Sum_当期AUM" >= 1000000
GROUP BY "Sub31_分组和汇总3"."机构编码__第二层时点机构号") "Sub40_分组和汇总11"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub40_分组和汇总11"."机构编码__第二层时点机构号"
)
LEFT JOIN (
(SELECT "Sub31_分组和汇总3"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
COUNT(DISTINCT "Sub31_分组和汇总3"."客户编号") AS "DistinctCount_客户编号"
FROM (
SELECT "Sub27_分组和汇总1"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub27_分组和汇总1"."客户编号" AS "客户编号"
, SUM(CASE WHEN "Sub27_分组和汇总1"."数据日期" = '20260430' THEN "Sub27_分组和汇总1"."Sum_月日均AUM" ELSE 0 END) AS "Sum_基期AUM"
, SUM(CASE WHEN "Sub27_分组和汇总1"."数据日期" = '20260519' THEN "Sub27_分组和汇总1"."Sum_月日均AUM" ELSE 0 END) AS "Sum_当期AUM"
FROM (
SELECT "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."客户编号" AS "客户编号",
SUM(CASE WHEN "Sub24_分组和汇总1_BASE"."数据日期" = '20260430' THEN "Sub24_分组和汇总1_BASE"."Sum_月日均AUM" ELSE 0 END) AS "Sum_基期AUM",
SUM(CASE WHEN "Sub24_分组和汇总1_BASE"."数据日期" = '20260519' THEN "Sub24_分组和汇总1_BASE"."Sum_月日均AUM" ELSE 0 END) AS "Sum_当期AUM"
FROM (
SELECT "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
'深圳市分行' AS "org", 
"Sub24_分组和汇总1_BASE"."客户编号" AS "客户编号", 
"Sub24_分组和汇总1_BASE"."数据日期" AS "数据日期",
"Sub24_分组和汇总1_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT "Sub21_分组和汇总_BASE"."机构编码__第二层时点机构号" AS "机构编码__第二层时点机构号", 
"Sub21_分组和汇总_BASE"."机构编码__第二层机构简称" AS "机构编码__第二层机构简称", 
"Sub21_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub21_分组和汇总_BASE"."数据日期" AS "数据日期",
SUM("Sub21_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub21_分组和汇总_BASE"
GROUP BY "Sub21_分组和汇总_BASE"."机构编码__第二层时点机构号", 
"Sub21_分组和汇总_BASE"."机构编码__第二层机构简称", 
"Sub21_分组和汇总_BASE"."客户编号", 
"Sub21_分组和汇总_BASE"."数据日期"
) "Sub24_分组和汇总1_BASE"
UNION ALL
SELECT "Sub26_分组和汇总2_BASE"."支行机构" AS "支行机构", 
"Sub26_分组和汇总2_BASE"."支行简称" AS "支行简称", 
"Sub26_分组和汇总2_BASE"."支行简称" AS "org", 
"Sub26_分组和汇总2_BASE"."客户编号" AS "客户编号", 
"Sub26_分组和汇总2_BASE"."数据日期" AS "数据日期",
"Sub26_分组和汇总2_BASE"."Sum_月日均AUM" AS "Sum_月日均AUM"
FROM (
SELECT CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层时点机构号"
END AS "支行机构",
CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层机构简称"
END AS "支行简称", 
"Sub21_分组和汇总_BASE"."客户编号" AS "客户编号", 
"Sub21_分组和汇总_BASE"."数据日期" AS "数据日期", 
SUM("Sub21_分组和汇总_BASE"."月日均AUM") AS "Sum_月日均AUM"
FROM (
SELECT
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 AS "机构编码__第四层时点机构号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4 AS "机构编码__第四层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 AS "机构编码__第三层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3 AS "机构编码__第三层机构简称",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 AS "机构编码__第二层时点机构号",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2 AS "机构编码__第二层机构简称", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO AS "客户编号", 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL AS "月日均AUM",
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE AS "数据日期"
FROM "BI_HQX00_V".BIM_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM
WHERE 1 = 1
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_0 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_1 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_5 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_6 = '41H006'
OR
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_7 = '41H006')
AND ((BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE >= '20260430'
AND BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE <= '20260519')
OR 'true' = 'false')
AND
(BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_LVL = 4
AND (BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260430'
OR BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE = '20260519'))
GROUP BY BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_4,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_3,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_NO_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__ORG_NO__BIO_PB_W_00_BI_STD_ORG__ORG_SNAM_2,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__CUST_NO, 
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__AUM_MAVER_BAL,
BIO_PB_W_00_I_WDM_PF_IDV_CUST_FA_SUM__DTE
) "Sub21_分组和汇总_BASE"
GROUP BY CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '41H002'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层时点机构号"
END, 
CASE "Sub21_分组和汇总_BASE"."机构编码__第四层时点机构号"
WHEN '410003' THEN '深圳市分行营业部'
ELSE "Sub21_分组和汇总_BASE"."机构编码__第三层机构简称"
END, 
"Sub21_分组和汇总_BASE"."客户编号", 
"Sub21_分组和汇总_BASE"."数据日期"
) "Sub26_分组和汇总2_BASE"
) "Sub24_分组和汇总1_BASE"
GROUP BY "Sub24_分组和汇总1_BASE"."机构编码__第二层时点机构号", 
"Sub24_分组和汇总1_BASE"."客户编号"
) "Sub27_分组和汇总1"
GROUP BY "Sub27_分组和汇总1"."机构编码__第二层时点机构号", 
"Sub27_分组和汇总1"."客户编号"
) "Sub31_分组和汇总3"
WHERE "Sub31_分组和汇总3"."Sum_基期AUM" < 1000000
AND "Sum_当期AUM" >= 1000000
AND "Sum_当期AUM" < 6000000
GROUP BY "Sub31_分组和汇总3"."机构编码__第二层时点机构号") "Sub41_分组和汇总12"
ON "Sub34_分组和汇总4"."机构编码__第二层时点机构号" = "Sub41_分组和汇总12"."机构编码__第二层时点机构号"
)
GROUP BY "Sub34_分组和汇总4"."机构编码__第二层时点机构号", 
"Sub34_分组和汇总4"."机构编码__第二层机构简称", 
"Sub34_分组和汇总4"."org", 
"Sub34_分组和汇总4"."DistinctCount_客户编号", 
"Sub39_分组和汇总9"."DistinctCount_客户编号", 
"Sub38_分组和汇总8"."DistinctCount_客户编号", 
"Sub37_分组和汇总7"."DistinctCount_客户编号", 
"Sub36_分组和汇总6"."DistinctCount_客户编号", 
"Sub35_分组和汇总5"."DistinctCount_客户编号", 
"Sub40_分组和汇总11"."DistinctCount_客户编号", 
"Sub41_分组和汇总12"."DistinctCount_客户编号"
) "Sub44_分组和汇总10_BASE"
GROUP BY "Sub44_分组和汇总10_BASE"."机构编码__第二层时点机构号", 
"Sub44_分组和汇总10_BASE"."机构编码__第二层机构简称", 
"Sub44_分组和汇总10_BASE"."org", 
"Sub44_分组和汇总10_BASE"."基期100", 
"Sub44_分组和汇总10_BASE"."基期100-600", 
"Sub44_分组和汇总10_BASE"."当期100", 
"Sub44_分组和汇总10_BASE"."当期100-600", 
"Sub44_分组和汇总10_BASE"."基期600", 
"Sub44_分组和汇总10_BASE"."当期600", 
"Sub44_分组和汇总10_BASE"."新增100", 
"Sub44_分组和汇总10_BASE"."新增100-600"
ORDER BY "Sub44_分组和汇总10_BASE"."org" ASC, 
"Sub44_分组和汇总10_BASE"."机构编码__第二层机构简称" ASC, 
"Sub44_分组和汇总10_BASE"."基期100" ASC, 
"Sub44_分组和汇总10_BASE"."当期100" ASC, 
"Sub44_分组和汇总10_BASE"."新增100" ASC, 
"Sub44_分组和汇总10_BASE"."新增100-600" ASC
LIMIT 9999999
) test01_subq_5;
