SET NAMES utf8mb4;

USE sqlforge;

INSERT INTO tenant_config (
  id,
  tenant_id,
  quota_concurrent,
  quota_storage,
  default_engine,
  backup_engine,
  audit_level,
  retention_days,
  acceleration_quota
) VALUES (
  1,
  'system',
  20,
  2048,
  'HETU',
  'HIVE',
  'NORMAL',
  180,
  50
)
ON DUPLICATE KEY UPDATE
  quota_concurrent = VALUES(quota_concurrent),
  quota_storage = VALUES(quota_storage),
  default_engine = VALUES(default_engine),
  backup_engine = VALUES(backup_engine),
  audit_level = VALUES(audit_level),
  retention_days = VALUES(retention_days),
  acceleration_quota = VALUES(acceleration_quota),
  update_time = CURRENT_TIMESTAMP;

INSERT INTO system_config (config_key, config_value, config_type, description) VALUES
  ('system.defaultEngine', 'HETU', 'STRING', 'Platform default execution engine'),
  ('system.backupEngine', 'HIVE', 'STRING', 'Platform fallback execution engine'),
  ('system.defaultAuditLevel', 'NORMAL', 'STRING', 'Platform default audit level'),
  ('system.auditRetentionDays', '180', 'INTEGER', 'Minimum audit log retention days'),
  ('system.backupPolicy', 'RPO<1h,RTO<4h,encrypted-backup-required', 'STRING', 'Backup and recovery baseline')
ON DUPLICATE KEY UPDATE
  config_value = VALUES(config_value),
  config_type = VALUES(config_type),
  description = VALUES(description),
  update_time = CURRENT_TIMESTAMP;

INSERT INTO metadata_snapshot (
  snapshot_id,
  tenant_id,
  datasource_code,
  object_type,
  object_key,
  object_name,
  catalog_name,
  schema_name,
  freshness_status,
  sla_status,
  queryability_status,
  evidence_status,
  latest_refresh_time,
  expected_sla_time,
  snapshot_time,
  evidence_source,
  column_count,
  partition_count,
  row_count,
  storage_bytes,
  request_id,
  trace_id,
  execution_id,
  history_id,
  parse_task_id,
  report_code,
  sql_fingerprint,
  upstream_refs_json,
  downstream_refs_json
) VALUES
  (
    'snapshot-001',
    'tenant-a',
    'hetu_main',
    'LOGICAL_VIEW',
    'LOGICAL_VIEW:RPT_SALES_DAILY',
    '每日销售',
    'lakehouse',
    'analytics',
    'FRESH',
    'ON_TRACK',
    'QUERYABLE',
    'CAPTURED',
    '2026-04-27 03:00:00',
    '2026-04-27 04:00:00',
    '2026-04-27 03:05:00',
    'GOVERNANCE_CATALOG',
    24,
    1,
    120000,
    67108864,
    'request-snapshot-001',
    'trace-snapshot-001',
    NULL,
    'history-001',
    NULL,
    'RPT_SALES_DAILY',
    'fp-sales-daily',
    '[{"objectType":"DB_VIEW","objectKey":"DB_VIEW:analytics.vw_sales_daily","objectName":"analytics.vw_sales_daily","relationshipType":"SOURCE"}]',
    '[{"objectType":"TABLE","objectKey":"TABLE:report.sales_daily_export","objectName":"report.sales_daily_export","relationshipType":"CONSUMED_BY"}]'
  ),
  (
    'snapshot-002',
    'tenant-a',
    'hetu_main',
    'DB_VIEW',
    'DB_VIEW:analytics.vw_sales_daily',
    'analytics.vw_sales_daily',
    'lakehouse',
    'analytics',
    'STALE',
    'AT_RISK',
    'QUERYABLE',
    'CAPTURED',
    '2026-04-26 02:00:00',
    '2026-04-27 01:00:00',
    '2026-04-27 03:05:00',
    'QUERY_HISTORY',
    18,
    2,
    980000,
    268435456,
    'request-snapshot-002',
    'trace-snapshot-002',
    'execution-002',
    'history-002',
    'parse-002',
    'RPT_SALES_DAILY',
    'fp-sales-daily',
    '[{"objectType":"TABLE","objectKey":"TABLE:sales.orders","objectName":"sales.orders","relationshipType":"SOURCE"},{"objectType":"TABLE","objectKey":"TABLE:sales.order_items","objectName":"sales.order_items","relationshipType":"SOURCE"}]',
    '[{"objectType":"LOGICAL_VIEW","objectKey":"LOGICAL_VIEW:RPT_SALES_DAILY","objectName":"每日销售","relationshipType":"EXPOSED_AS"}]'
  ),
  (
    'snapshot-003',
    'tenant-a',
    'hetu_main',
    'TABLE',
    'TABLE:sales.orders',
    'sales.orders',
    'lakehouse',
    'sales',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    48,
    12,
    1280000,
    536870912,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[]',
    '[{"objectType":"DB_VIEW","objectKey":"DB_VIEW:analytics.vw_sales_daily","objectName":"analytics.vw_sales_daily","relationshipType":"CONSUMED_BY"}]'
  )
ON DUPLICATE KEY UPDATE
  datasource_code = VALUES(datasource_code),
  object_type = VALUES(object_type),
  object_name = VALUES(object_name),
  catalog_name = VALUES(catalog_name),
  schema_name = VALUES(schema_name),
  freshness_status = VALUES(freshness_status),
  sla_status = VALUES(sla_status),
  queryability_status = VALUES(queryability_status),
  evidence_status = VALUES(evidence_status),
  latest_refresh_time = VALUES(latest_refresh_time),
  expected_sla_time = VALUES(expected_sla_time),
  snapshot_time = VALUES(snapshot_time),
  evidence_source = VALUES(evidence_source),
  column_count = VALUES(column_count),
  partition_count = VALUES(partition_count),
  row_count = VALUES(row_count),
  storage_bytes = VALUES(storage_bytes),
  request_id = VALUES(request_id),
  trace_id = VALUES(trace_id),
  execution_id = VALUES(execution_id),
  history_id = VALUES(history_id),
  parse_task_id = VALUES(parse_task_id),
  report_code = VALUES(report_code),
  sql_fingerprint = VALUES(sql_fingerprint),
  upstream_refs_json = VALUES(upstream_refs_json),
  downstream_refs_json = VALUES(downstream_refs_json),
  update_time = CURRENT_TIMESTAMP;

INSERT INTO system_dictionary (
  dictionary_type,
  dictionary_code,
  dictionary_name,
  sort_order,
  enabled_flag,
  remark
) VALUES
  ('dataSourceType', 'HETU', 'Hetu', 1, 1, 'Default distributed SQL engine'),
  ('dataSourceType', 'HIVE', 'Hive', 2, 1, 'Hive SQL engine'),
  ('dataSourceType', 'SPARK', 'Spark', 3, 1, 'Spark SQL engine'),
  ('dataSourceType', 'CLICKHOUSE', 'ClickHouse', 4, 1, 'ClickHouse analytical engine'),
  ('dataSourceType', 'GAUSSDB', 'GaussDB', 5, 1, 'GaussDB engine'),
  ('dataSourceType', 'AUTO', 'Auto Route', 6, 1, 'Route automatically by governance rules'),
  ('accelerationType', 'PRECOMPUTE', 'Precompute', 1, 1, 'Precompute acceleration'),
  ('accelerationType', 'PARTITION', 'Partition', 2, 1, 'Partition acceleration'),
  ('accelerationType', 'BUCKET', 'Bucket', 3, 1, 'Bucket acceleration'),
  ('accelerationType', 'SPLIT', 'Split', 4, 1, 'Split acceleration'),
  ('accelerationType', 'REPLACE', 'Replace', 5, 1, 'Replace acceleration'),
  ('messagingStatus', 'PENDING', 'Pending', 1, 1, 'R-144 database queue pending message'),
  ('messagingStatus', 'SENT', 'Sent', 2, 1, 'R-144 database queue sent message'),
  ('messagingStatus', 'CONSUMED', 'Consumed', 3, 1, 'R-144 database queue consumed message'),
  ('messagingStatus', 'FAILED', 'Failed', 4, 1, 'R-144 database queue failed message'),
  ('auditLevel', 'STRICT', 'Strict', 1, 1, 'High risk statements require strict review'),
  ('auditLevel', 'NORMAL', 'Normal', 2, 1, 'Default audit review level'),
  ('auditLevel', 'LOOSE', 'Loose', 3, 1, 'Record only with low intervention')
ON DUPLICATE KEY UPDATE
  dictionary_name = VALUES(dictionary_name),
  sort_order = VALUES(sort_order),
  enabled_flag = VALUES(enabled_flag),
  remark = VALUES(remark),
  update_time = CURRENT_TIMESTAMP;
