SET NAMES utf8mb4;
SET time_zone = '+08:00';

CREATE DATABASE IF NOT EXISTS sqlforge
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE sqlforge;

-- SQLForge initialization schema
-- Compliance notes:
-- 1. audit_log must use dedicated storage/tablespace strategy in production operations.
-- 2. Encrypted fields must store AES-256 or SM4 ciphertext only, never plaintext.
-- 3. Backup target: RPO < 1 hour, RTO < 4 hours, encrypted backup media.
-- 4. 所有 DATETIME/CURRENT_TIMESTAMP 字段统一按北京时间（Asia/Shanghai，24 小时制）管理和展示。

CREATE TABLE IF NOT EXISTS tenant_config (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符，平台内唯一',
  quota_concurrent INT NOT NULL DEFAULT 10 COMMENT '每租户最大并发查询数',
  quota_storage BIGINT NOT NULL DEFAULT 1024 COMMENT '存储配额，单位 GB',
  default_engine VARCHAR(32) NOT NULL COMMENT '默认执行引擎',
  backup_engine VARCHAR(32) NOT NULL COMMENT '兜底执行引擎',
  audit_level VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '审计评审级别：STRICT/NORMAL/LOOSE',
  retention_days INT NOT NULL DEFAULT 180 COMMENT '保留策略天数',
  acceleration_quota INT NOT NULL DEFAULT 20 COMMENT '加速配置配额',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_config_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tenant governance configuration';

CREATE TABLE IF NOT EXISTS kafka_message_queue (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  topic VARCHAR(128) NOT NULL COMMENT '模拟 Kafka 主题',
  partition_key VARCHAR(128) DEFAULT NULL COMMENT '分区键',
  message_body TEXT NOT NULL COMMENT 'JSON 消息正文',
  headers TEXT DEFAULT NULL COMMENT 'JSON 请求头',
  status ENUM('PENDING','SENT','CONSUMED','FAILED') NOT NULL DEFAULT 'PENDING' COMMENT '消息状态',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  consumed_at TIMESTAMP NULL DEFAULT NULL COMMENT '消费时间',
  error_log TEXT DEFAULT NULL COMMENT '错误日志',
  PRIMARY KEY (id),
  KEY idx_topic_status (topic, status),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='R-144数据库模拟模式消息队列';

CREATE TABLE IF NOT EXISTS sql_query_job (
  job_id VARCHAR(64) NOT NULL COMMENT 'SQL 查询作业标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  sql_text MEDIUMBLOB NOT NULL COMMENT '加密 SQL 文本载荷，仅保存密文',
  parse_mode VARCHAR(16) NOT NULL DEFAULT 'LIGHT' COMMENT '解析模式：LIGHT/DEEP',
  data_source_type VARCHAR(32) NOT NULL COMMENT '数据源类型',
  status VARCHAR(32) NOT NULL COMMENT '作业状态',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  finish_time DATETIME NULL DEFAULT NULL COMMENT '结束时间戳',
  PRIMARY KEY (job_id),
  KEY idx_sql_query_job_tenant_time (tenant_id, create_time),
  KEY idx_sql_query_job_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SQL lifecycle query jobs';

CREATE TABLE IF NOT EXISTS execution_plan (
  plan_id VARCHAR(64) NOT NULL COMMENT '执行计划标识符',
  job_id VARCHAR(64) NOT NULL COMMENT '关联查询作业标识符',
  target_engine VARCHAR(32) NOT NULL COMMENT '已选择执行引擎',
  fallback_engine VARCHAR(32) DEFAULT NULL COMMENT '已配置兜底引擎',
  ast_summary JSON NULL COMMENT 'AST 摘要载荷',
  estimated_cost DECIMAL(18,4) DEFAULT NULL COMMENT '预估执行成本',
  actual_cost DECIMAL(18,4) DEFAULT NULL COMMENT '实际执行成本',
  degraded_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示已应用兜底或降级模式',
  PRIMARY KEY (plan_id),
  KEY idx_execution_plan_job_id (job_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Execution plans and fallback metadata';

CREATE TABLE IF NOT EXISTS benchmark_task (
  task_id VARCHAR(64) NOT NULL COMMENT '压测任务标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  task_type VARCHAR(32) NOT NULL COMMENT '压测任务类型：BASELINE/COMPARISON/REGRESSION_GUARD',
  sql_text LONGTEXT DEFAULT NULL COMMENT '已提交 SQL 文本快照',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '归一化 SQL 指纹',
  priority VARCHAR(16) NOT NULL COMMENT '任务优先级',
  target_engines_json JSON NOT NULL COMMENT '请求的目标引擎列表 JSON',
  concurrency INT DEFAULT NULL COMMENT '请求的压测并发数',
  duration_seconds INT DEFAULT NULL COMMENT '请求的压测持续秒数',
  ramp_up_seconds INT DEFAULT NULL COMMENT '请求的预热爬坡秒数',
  dataset_size_label VARCHAR(64) DEFAULT NULL COMMENT '数据集规模标签',
  scale_target_json JSON DEFAULT NULL COMMENT '生产规模目标与未验证证据边界 JSON',
  template_id VARCHAR(64) DEFAULT NULL COMMENT '压测模板标识符',
  template_type VARCHAR(32) DEFAULT NULL COMMENT '压测模板类型',
  template_version VARCHAR(32) DEFAULT NULL COMMENT '压测模板契约版本',
  test_set_id VARCHAR(64) DEFAULT NULL COMMENT '压测测试集标识符',
  test_set_source VARCHAR(32) DEFAULT NULL COMMENT '压测测试集来源类型',
  test_set_labels_json JSON DEFAULT NULL COMMENT '压测测试集标签模型 JSON',
  test_set_source_refs_json JSON DEFAULT NULL COMMENT '压测测试集来源引用 JSON',
  readonly_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT '只读护栏标志',
  shadow_environment_mode VARCHAR(32) NOT NULL COMMENT '影子环境要求模式',
  desensitization_requirement VARCHAR(32) NOT NULL COMMENT '脱敏要求模式',
  thresholds_json JSON NOT NULL COMMENT '阈值定义 JSON',
  status VARCHAR(16) NOT NULL COMMENT 'Task 状态：QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  current_phase VARCHAR(32) NOT NULL COMMENT '当前任务阶段',
  progress_percent INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
  report_id VARCHAR(64) DEFAULT NULL COMMENT '可用时生成的报告标识符',
  error_code INT DEFAULT NULL COMMENT '失败码',
  error_message VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的失败消息',
  error_suggested_action VARCHAR(512) DEFAULT NULL COMMENT '建议的后续处理动作',
  error_retryable TINYINT(1) DEFAULT NULL COMMENT '失败是否可重试',
  status_history_json JSON NOT NULL COMMENT '有序状态流转历史 JSON',
  submitted_at DATETIME(3) NOT NULL COMMENT '提交时间戳',
  started_at DATETIME(3) DEFAULT NULL COMMENT 'Worker 启动时间戳',
  finished_at DATETIME(3) DEFAULT NULL COMMENT '结束时间戳',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (task_id),
  KEY idx_benchmark_task_status_submitted (status, submitted_at),
  KEY idx_benchmark_task_tenant_time (tenant_id, create_time),
  KEY idx_benchmark_task_fingerprint (sql_fingerprint),
  KEY idx_benchmark_task_template_type (template_type),
  KEY idx_benchmark_task_test_set_source (test_set_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Persistent benchmark task carrier for scheduler and worker flow';

CREATE TABLE IF NOT EXISTS benchmark_task_report (
  report_id VARCHAR(64) NOT NULL COMMENT '压测报告标识符',
  task_id VARCHAR(64) NOT NULL COMMENT '关联压测 task标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  task_type VARCHAR(32) NOT NULL COMMENT '压测任务类型',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '归一化 SQL 指纹',
  generated_at DATETIME(3) NOT NULL COMMENT '报告生成时间戳',
  verdict VARCHAR(32) NOT NULL COMMENT '报告结论',
  engine_profiles_json JSON NOT NULL COMMENT '按引擎统计的压测指标 JSON',
  threshold_assessments_json JSON NOT NULL COMMENT '阈值评估 JSON',
  recommendations_json JSON NOT NULL COMMENT '推荐列表 JSON',
  execution_summary_json JSON DEFAULT NULL COMMENT '隔离执行摘要 JSON',
  regression_summary_json JSON DEFAULT NULL COMMENT '回归摘要 JSON',
  alert_linkages_json JSON DEFAULT NULL COMMENT '治理告警关联 JSON',
  export_artifacts_json JSON DEFAULT NULL COMMENT '已持久化导出制品元数据与内容 JSON',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (report_id),
  UNIQUE KEY uk_benchmark_task_report_task_id (task_id),
  KEY idx_benchmark_task_report_tenant_time (tenant_id, create_time),
  KEY idx_benchmark_task_report_fingerprint (sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Persistent benchmark reports written back by the benchmark worker';

CREATE TABLE IF NOT EXISTS optimization_task (
  task_id VARCHAR(64) NOT NULL COMMENT '优化任务标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  task_type VARCHAR(32) NOT NULL COMMENT '优化任务类型：PARSE/REWRITE/ACCELERATION_SUGGESTION',
  sql_text LONGTEXT DEFAULT NULL COMMENT '已提交 SQL 文本快照',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '归一化 SQL 指纹',
  datasource_type VARCHAR(32) NOT NULL COMMENT '数据源类型',
  priority VARCHAR(16) NOT NULL COMMENT '任务优先级',
  parse_depth VARCHAR(16) NOT NULL COMMENT '解析深度',
  callback_url VARCHAR(2048) DEFAULT NULL COMMENT '可选回调 URL',
  requested_suggestion_types_json JSON DEFAULT NULL COMMENT '请求的加速建议类型 JSON',
  task_context_json JSON DEFAULT NULL COMMENT '解析触发任务的来源上下文 JSON',
  status VARCHAR(16) NOT NULL COMMENT 'Task 状态：QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  current_phase VARCHAR(32) NOT NULL COMMENT '当前任务阶段',
  progress_percent INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
  summary TEXT DEFAULT NULL COMMENT '任务完成时的摘要',
  suggestion_payload_json JSON DEFAULT NULL COMMENT '结构化建议载荷 JSON',
  error_code INT DEFAULT NULL COMMENT '失败码',
  error_message VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的失败消息',
  error_suggested_action VARCHAR(512) DEFAULT NULL COMMENT '建议的后续处理动作',
  error_retryable TINYINT(1) DEFAULT NULL COMMENT '失败是否可重试',
  failed_phase VARCHAR(32) DEFAULT NULL COMMENT '产生失败的执行阶段',
  error_risks_json JSON DEFAULT NULL COMMENT '结构化失败风险 JSON',
  status_history_json JSON NOT NULL COMMENT '有序状态流转历史 JSON',
  submitted_at DATETIME(3) NOT NULL COMMENT '提交时间戳',
  started_at DATETIME(3) DEFAULT NULL COMMENT 'Worker 启动时间戳',
  finished_at DATETIME(3) DEFAULT NULL COMMENT '结束时间戳',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (task_id),
  KEY idx_optimization_task_status_submitted (status, submitted_at),
  KEY idx_optimization_task_tenant_time (tenant_id, create_time),
  KEY idx_optimization_task_fingerprint (sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Persistent SQL optimization task carrier for scheduler and worker flow';

CREATE TABLE IF NOT EXISTS acceleration_plan (
  plan_id VARCHAR(64) NOT NULL COMMENT '加速计划标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  source_task_id VARCHAR(64) NOT NULL COMMENT '来源优化任务标识符',
  sql_text LONGTEXT DEFAULT NULL COMMENT '已提交 SQL 文本快照',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '归一化 SQL 指纹',
  datasource_type VARCHAR(32) NOT NULL COMMENT '数据源类型',
  selected_suggestion_types_json JSON NOT NULL COMMENT '已选择的加速建议类型 JSON',
  plan_status VARCHAR(32) NOT NULL COMMENT '计划状态：READY/ACTIVE/PAUSED/ACTIVATE_FAILED/PAUSE_FAILED',
  plan_summary TEXT DEFAULT NULL COMMENT '计划摘要',
  primary_recommendation TEXT DEFAULT NULL COMMENT '主要推荐',
  plan_payload_json JSON NOT NULL COMMENT '已选择的加速计划载荷 JSON',
  benefits_json JSON DEFAULT NULL COMMENT '结构化收益 JSON',
  costs_json JSON DEFAULT NULL COMMENT '结构化成本 JSON',
  risks_json JSON DEFAULT NULL COMMENT '结构化风险 JSON',
  config_snapshot_id VARCHAR(64) DEFAULT NULL COMMENT '治理配置快照标识符',
  result_id VARCHAR(64) DEFAULT NULL COMMENT '治理执行结果标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '治理查询历史标识符',
  last_error_code INT DEFAULT NULL COMMENT '最近一次生命周期失败码',
  last_error_message VARCHAR(512) DEFAULT NULL COMMENT '最近一次生命周期失败消息',
  activation_evidence_json JSON DEFAULT NULL COMMENT '激活运行时证据 JSON',
  activated_at DATETIME(3) DEFAULT NULL COMMENT '激活时间戳',
  activated_by VARCHAR(64) DEFAULT NULL COMMENT '激活操作人标识符',
  pause_evidence_json JSON DEFAULT NULL COMMENT '暂停运行时证据 JSON',
  paused_at DATETIME(3) DEFAULT NULL COMMENT '暂停时间戳',
  paused_by VARCHAR(64) DEFAULT NULL COMMENT '暂停操作人标识符',
  status_history_json JSON NOT NULL COMMENT '有序计划状态流转历史 JSON',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  updated_at DATETIME(3) NOT NULL COMMENT '最后更新时间戳',
  PRIMARY KEY (plan_id),
  KEY idx_acceleration_plan_status_created (plan_status, created_at),
  KEY idx_acceleration_plan_tenant_time (tenant_id, created_at),
  KEY idx_acceleration_plan_fingerprint (sql_fingerprint),
  KEY idx_acceleration_plan_source_task (source_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed acceleration plan lifecycle carrier';

CREATE TABLE IF NOT EXISTS acceleration_config (
  config_id VARCHAR(64) NOT NULL COMMENT '加速配置标识符',
  sql_fingerprint CHAR(32) NOT NULL COMMENT 'SQL 指纹',
  acceleration_type VARCHAR(32) NOT NULL COMMENT '加速类型：PRECOMPUTE/PARTITION/BUCKET/SPLIT/REPLACE',
  config_detail_json JSON NOT NULL COMMENT '加速配置明细',
  status VARCHAR(16) NOT NULL COMMENT '配置状态：DRAFT/ACTIVE/INVALID/DEPRECATED',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  invalid_time DATETIME NULL DEFAULT NULL COMMENT '失效时间戳',
  PRIMARY KEY (config_id),
  KEY idx_acceleration_config_fingerprint (sql_fingerprint),
  KEY idx_acceleration_config_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Acceleration strategy configurations';

CREATE TABLE IF NOT EXISTS config_snapshot (
  config_snapshot_id VARCHAR(64) NOT NULL COMMENT '配置快照标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  service_code VARCHAR(32) NOT NULL COMMENT '归属服务编码',
  source_config_type VARCHAR(32) NOT NULL COMMENT '来源配置类型，例如 TENANT_CONFIG/SYSTEM_CONFIG/ACCELERATION_CONFIG',
  source_config_id VARCHAR(128) NOT NULL COMMENT '来源配置业务标识符',
  source_version VARCHAR(64) DEFAULT NULL COMMENT '可选来源配置版本',
  snapshot_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '快照状态：ACTIVE/DEPRECATED/ROLLED_BACK',
  snapshot_reason VARCHAR(128) DEFAULT NULL COMMENT '快照原因，例如 TASK_SUBMIT/EXPORT_REQUEST/AUDIT_REPLAY',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  saga_id VARCHAR(64) DEFAULT NULL COMMENT '跨服务补偿链 Saga 标识符',
  snapshot_payload JSON NOT NULL COMMENT '敏感叶子节点已加密的配置快照载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  PRIMARY KEY (config_snapshot_id),
  KEY idx_config_snapshot_tenant_time (tenant_id, create_time),
  KEY idx_config_snapshot_source (source_config_type, source_config_id),
  KEY idx_config_snapshot_trace (trace_id, request_id),
  KEY idx_config_snapshot_status (snapshot_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Immutable configuration snapshots used as the traceability anchor';

CREATE TABLE IF NOT EXISTS execution_result (
  result_id VARCHAR(64) NOT NULL COMMENT '执行结果标识符',
  config_snapshot_id VARCHAR(64) NOT NULL COMMENT '引用的配置快照标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  service_code VARCHAR(32) NOT NULL COMMENT '归属服务编码',
  task_id VARCHAR(64) DEFAULT NULL COMMENT '关联任务标识符',
  task_type VARCHAR(32) NOT NULL COMMENT '任务类型，例如 QUERY_EXECUTION/OPTIMIZATION/BENCHMARK',
  result_status VARCHAR(16) NOT NULL COMMENT '结果状态：QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  saga_id VARCHAR(64) DEFAULT NULL COMMENT '跨服务补偿链 Saga 标识符',
  access_channel VARCHAR(32) DEFAULT NULL COMMENT '访问渠道，例如 PAGE/API/JDBC_AGENT/SDK/CLIENT',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '已选择执行引擎或路由引擎',
  returned_row_count BIGINT DEFAULT NULL COMMENT '已知时的返回行数',
  cache_hit TINYINT(1) DEFAULT NULL COMMENT '是否命中缓存',
  rewrite_applied TINYINT(1) DEFAULT NULL COMMENT '是否应用轻量改写',
  acceleration_applied TINYINT(1) DEFAULT NULL COMMENT '是否应用加速路径',
  hit_table_summary JSON DEFAULT NULL COMMENT '结构化命中表摘要 JSON',
  route_summary JSON DEFAULT NULL COMMENT '结构化路由摘要 JSON',
  cache_summary JSON DEFAULT NULL COMMENT '结构化缓存摘要 JSON',
  result_summary JSON DEFAULT NULL COMMENT '不含敏感数据的结构化摘要',
  result_payload JSON DEFAULT NULL COMMENT '敏感叶子节点已加密的结构化结果载荷',
  error_code VARCHAR(32) DEFAULT NULL COMMENT '失败时的错误码',
  error_message VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的错误消息',
  started_at DATETIME DEFAULT NULL COMMENT '开始时间',
  finished_at DATETIME DEFAULT NULL COMMENT '结束时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  PRIMARY KEY (result_id),
  KEY idx_execution_result_tenant_time (tenant_id, create_time),
  KEY idx_execution_result_task (task_id, task_type),
  KEY idx_execution_result_trace (trace_id, request_id),
  KEY idx_execution_result_status (result_status),
  KEY idx_execution_result_config_snapshot_id (config_snapshot_id),
  KEY idx_execution_result_access_channel (tenant_id, access_channel, create_time),
  KEY idx_execution_result_target_engine (tenant_id, target_engine, create_time),
  KEY idx_execution_result_cache_hit (tenant_id, cache_hit, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Immutable execution and analysis results';

CREATE TABLE IF NOT EXISTS query_history (
  history_id VARCHAR(64) NOT NULL COMMENT '查询历史标识符',
  result_id VARCHAR(64) NOT NULL COMMENT '引用的执行结果标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  history_type VARCHAR(32) NOT NULL COMMENT '历史类型，例如 QUERY_EXECUTION/SQL_OPTIMIZATION/BENCHMARK',
  sql_fingerprint CHAR(32) NOT NULL COMMENT '归一化 SQL 指纹',
  sql_text_cipher MEDIUMBLOB DEFAULT NULL COMMENT '加密 SQL 文本载荷，仅保存密文',
  sql_template_cipher MEDIUMBLOB DEFAULT NULL COMMENT '参数化查询的加密模板 SQL 载荷',
  bound_sql_text_cipher MEDIUMBLOB DEFAULT NULL COMMENT '参数绑定后的加密绑定 SQL 载荷',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源业务标识符或别名',
  datasource_type VARCHAR(32) DEFAULT NULL COMMENT '数据源类型',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的报表编码',
  stage_code VARCHAR(32) DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的执行阶段',
  biz_date DATE DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的执行日期',
  query_date_start DATE DEFAULT NULL COMMENT '从 SQL 正文解析出的查询日期下界',
  query_date_end DATE DEFAULT NULL COMMENT '从 SQL 正文解析出的查询日期上界',
  query_date_status VARCHAR(32) DEFAULT NULL COMMENT '查询日期提取状态，例如 RESOLVED/UNRESOLVED/PARTIAL',
  access_channel VARCHAR(32) DEFAULT NULL COMMENT '访问渠道，例如 PAGE/API/JDBC_AGENT/SDK/CLIENT',
  parameterized_sql_flag TINYINT(1) DEFAULT NULL COMMENT '绑定前 SQL 是否已参数化',
  binding_mode VARCHAR(16) DEFAULT NULL COMMENT 'Binding 模式，例如 POSITIONAL/NAMED',
  binding_render_status VARCHAR(16) DEFAULT NULL COMMENT '绑定渲染状态，例如 SUCCESS/PARTIAL/FAILED/MASKED',
  sql_template_fingerprint CHAR(32) DEFAULT NULL COMMENT '绑定前模板 SQL 指纹',
  bound_sql_fingerprint CHAR(32) DEFAULT NULL COMMENT '绑定后 SQL 指纹',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  saga_id VARCHAR(64) DEFAULT NULL COMMENT '跨服务补偿链 Saga 标识符',
  comment_context JSON DEFAULT NULL COMMENT '结构化 SQL 注释上下文 JSON',
  binding_summary JSON DEFAULT NULL COMMENT '结构化参数绑定摘要 JSON',
  rewrite_record_id VARCHAR(64) DEFAULT NULL COMMENT '本次执行已应用或评估的 SQL 改写记录标识符',
  runtime_binding_id VARCHAR(64) DEFAULT NULL COMMENT 'query-execution 使用的运行时改写绑定标识符',
  rewrite_rule_version BIGINT DEFAULT NULL COMMENT '数值型运行时改写规则版本快照',
  runtime_rule_version VARCHAR(64) DEFAULT NULL COMMENT '运行时改写规则版本标签快照',
  runtime_rewrite_status VARCHAR(32) DEFAULT NULL COMMENT '运行时改写绑定解析状态快照',
  rewrite_activation_status_snapshot VARCHAR(32) DEFAULT NULL COMMENT '从后端运行时证据派生的激活状态快照',
  rewrite_fallback_reason VARCHAR(128) DEFAULT NULL COMMENT '自动改写回退到原始 SQL 的原因',
  logical_object_hits JSON DEFAULT NULL COMMENT '结构化逻辑对象与表命中摘要 JSON',
  route_summary JSON DEFAULT NULL COMMENT '结构化路由决策摘要 JSON',
  cache_summary JSON DEFAULT NULL COMMENT '结构化缓存决策摘要 JSON',
  query_context JSON DEFAULT NULL COMMENT '敏感叶子节点已加密的结构化查询上下文',
  submitted_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间戳',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  PRIMARY KEY (history_id),
  KEY idx_query_history_result_id (result_id),
  KEY idx_query_history_tenant_time (tenant_id, create_time),
  KEY idx_query_history_fingerprint (sql_fingerprint),
  KEY idx_query_history_trace (trace_id, request_id),
  KEY idx_query_history_report_stage_date (tenant_id, report_code, stage_code, biz_date),
  KEY idx_query_history_query_date (tenant_id, query_date_start, query_date_end),
  KEY idx_query_history_datasource_code (tenant_id, datasource_code, create_time),
  KEY idx_query_history_access_channel (tenant_id, access_channel, create_time),
  KEY idx_query_history_binding_mode (tenant_id, binding_mode, create_time),
  KEY idx_query_history_rewrite_record (tenant_id, rewrite_record_id, create_time),
  KEY idx_query_history_runtime_binding (tenant_id, runtime_binding_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Historical immutable query snapshots linked to execution results';

CREATE TABLE IF NOT EXISTS export_record (
  export_id VARCHAR(64) NOT NULL COMMENT '导出记录标识符',
  history_id VARCHAR(64) NOT NULL COMMENT '引用的查询历史标识符',
  result_id VARCHAR(64) NOT NULL COMMENT '引用的执行结果标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  export_format VARCHAR(16) NOT NULL COMMENT '导出格式：JSON/PDF/HTML/CSV',
  export_status VARCHAR(16) NOT NULL COMMENT '导出状态：REQUESTED/GENERATING/READY/FAILED/EXPIRED',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  saga_id VARCHAR(64) DEFAULT NULL COMMENT '跨服务补偿链 Saga 标识符',
  storage_type VARCHAR(32) DEFAULT NULL COMMENT '存储类型，例如 INLINE/MINIO/OSS',
  storage_uri VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的导出存储位置',
  checksum VARCHAR(128) DEFAULT NULL COMMENT '导出校验和',
  export_options JSON DEFAULT NULL COMMENT '敏感叶子节点已加密的结构化导出选项',
  error_code VARCHAR(32) DEFAULT NULL COMMENT '失败时的错误码',
  error_message VARCHAR(512) DEFAULT NULL COMMENT '脱敏后的错误消息',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  finished_at DATETIME DEFAULT NULL COMMENT '结束时间戳',
  PRIMARY KEY (export_id),
  KEY idx_export_record_history_id (history_id),
  KEY idx_export_record_result_id (result_id),
  KEY idx_export_record_tenant_time (tenant_id, create_time),
  KEY idx_export_record_trace (trace_id, request_id),
  KEY idx_export_record_status (export_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Export metadata and immutable render outputs';

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '审计日志主键',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  service_code VARCHAR(32) DEFAULT NULL COMMENT '用于可追踪性的归属服务编码',
  operation_type VARCHAR(64) NOT NULL COMMENT '操作类型，例如 LOGIN、QUERY、PERMISSION_CHANGE',
  target_type VARCHAR(64) NOT NULL COMMENT '目标类型，例如 SQL_JOB、DATASOURCE、USER',
  target_id VARCHAR(128) NOT NULL COMMENT '目标业务标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  saga_id VARCHAR(64) DEFAULT NULL COMMENT '用于跨服务补偿链的 Saga 标识符',
  config_snapshot_id VARCHAR(64) DEFAULT NULL COMMENT '引用的配置快照标识符',
  result_id VARCHAR(64) DEFAULT NULL COMMENT '引用的执行结果标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '引用的查询历史标识符',
  export_id VARCHAR(64) DEFAULT NULL COMMENT '引用的导出记录标识符',
  request_params JSON NULL COMMENT '脱敏后的请求参数，不允许包含原始密钥',
  response_summary TEXT NULL COMMENT '不含敏感数据的响应摘要',
  status VARCHAR(16) NOT NULL COMMENT '操作结果：SUCCESS/FAILED/PARTIAL',
  cost_ms BIGINT NOT NULL DEFAULT 0 COMMENT '处理耗时，单位毫秒',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '审计创建时间，至少保留 180 天',
  PRIMARY KEY (id),
  KEY idx_audit_log_tenant_time (tenant_id, create_time),
  KEY idx_audit_log_operation_time (operation_type, create_time),
  KEY idx_audit_log_target (target_type, target_id),
  KEY idx_audit_log_trace_request (trace_id, request_id),
  KEY idx_audit_log_config_snapshot_id (config_snapshot_id),
  KEY idx_audit_log_result_id (result_id),
  KEY idx_audit_log_history_id (history_id),
  KEY idx_audit_log_export_id (export_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Immutable audit logs, production should isolate storage strategy';

CREATE TABLE IF NOT EXISTS alert_policy (
  policy_id VARCHAR(64) NOT NULL COMMENT '告警策略标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  policy_name VARCHAR(128) NOT NULL COMMENT '可读告警策略名称',
  alert_type VARCHAR(64) NOT NULL COMMENT '告警类型，例如 DATASOURCE_UNAVAILABLE 或 AUDIT_WRITE_EXCEPTION',
  default_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT '默认告警级别：LOW/MEDIUM/HIGH/CRITICAL',
  dedupe_strategy VARCHAR(32) NOT NULL DEFAULT 'TENANT_ALERT_TYPE_TARGET' COMMENT '去重策略基线',
  dedupe_window_seconds INT NOT NULL DEFAULT 900 COMMENT '去重窗口秒数',
  notify_channel VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_EMAIL' COMMENT '通知渠道基线',
  initial_notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT '初始通知状态：SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  owner_scope VARCHAR(64) NOT NULL DEFAULT 'TENANT_SCOPE' COMMENT '策略所属数据范围',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '策略是否启用',
  rule_config_json JSON DEFAULT NULL COMMENT '结构化阈值或匹配器基线 JSON',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  updated_at DATETIME(3) NOT NULL COMMENT '最后更新时间戳',
  PRIMARY KEY (policy_id),
  UNIQUE KEY uk_alert_policy_tenant_type (tenant_id, alert_type),
  KEY idx_alert_policy_tenant_enabled (tenant_id, enabled, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert policy baseline for dedupe, severity, and simulated notify defaults';

CREATE TABLE IF NOT EXISTS alert_event (
  alert_id VARCHAR(64) NOT NULL COMMENT '告警事件标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  alert_type VARCHAR(64) NOT NULL COMMENT '告警类型，例如 DATASOURCE_UNAVAILABLE 或 BENCHMARK_REGRESSION_FAILED',
  alert_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT '告警严重级别：LOW/MEDIUM/HIGH/CRITICAL',
  alert_status VARCHAR(16) NOT NULL DEFAULT 'OPEN' COMMENT '告警生命周期状态：OPEN/ACKED',
  notify_status VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_PENDING_NOTIFY' COMMENT '通知状态：SIMULATED_PENDING_NOTIFY/SIMULATED_NOTIFIED/SIMULATED_NOTIFY_FAILED',
  policy_id VARCHAR(64) DEFAULT NULL COMMENT '所属告警策略标识符',
  dedupe_key VARCHAR(255) NOT NULL COMMENT '租户范围内去重键',
  source_service VARCHAR(64) DEFAULT NULL COMMENT '来源服务编码或来源界面',
  summary VARCHAR(512) NOT NULL COMMENT '面向操作人的告警摘要',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse task标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '关联批次标识符',
  route_decision_id VARCHAR(64) DEFAULT NULL COMMENT '关联路由决策标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联推荐标识符',
  dispatch_event_id VARCHAR(64) DEFAULT NULL COMMENT '关联分发事件标识符',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  datasource_id VARCHAR(128) DEFAULT NULL COMMENT '关联数据源标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  evidence_json JSON DEFAULT NULL COMMENT '结构化证据载荷',
  notify_message VARCHAR(512) DEFAULT NULL COMMENT '最近一次模拟通知结果消息',
  notified_at DATETIME(3) DEFAULT NULL COMMENT '最近一次模拟通知时间戳',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT '确认操作人标识符',
  acked_at DATETIME(3) DEFAULT NULL COMMENT '确认时间戳',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  updated_at DATETIME(3) NOT NULL COMMENT '最后更新时间戳',
  PRIMARY KEY (alert_id),
  KEY idx_alert_event_tenant_status_created (tenant_id, alert_status, created_at),
  KEY idx_alert_event_tenant_dedupe_created (tenant_id, dedupe_key, created_at),
  KEY idx_alert_event_tenant_type_created (tenant_id, alert_type, created_at),
  KEY idx_alert_event_tenant_dispatch (tenant_id, dispatch_event_id, created_at),
  KEY idx_alert_event_tenant_recommendation (tenant_id, recommendation_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alert event carrier for simulated notify, dedupe, and future ACK flow';

CREATE TABLE IF NOT EXISTS alert_notification_log (
  notification_log_id VARCHAR(96) NOT NULL COMMENT '告警通知日志标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  alert_id VARCHAR(64) NOT NULL COMMENT '作为持久化来源使用的告警事件标识符',
  source_alert_id VARCHAR(64) DEFAULT NULL COMMENT '通知被抑制时的原始去重来源告警标识符',
  dedupe_key VARCHAR(255) NOT NULL COMMENT '租户范围内去重键',
  notify_channel VARCHAR(32) NOT NULL DEFAULT 'SIMULATED_EMAIL' COMMENT '通知渠道，第一阶段仅模拟',
  delivery_status VARCHAR(32) NOT NULL COMMENT '投递状态：SIMULATED_SENT/DEDUPE_SUPPRESSED/SIMULATED_FAILED',
  template_code VARCHAR(64) NOT NULL COMMENT '已渲染模板标识符',
  message_subject VARCHAR(255) NOT NULL COMMENT '已渲染模拟消息主题',
  message_body TEXT NOT NULL COMMENT '已渲染模拟消息正文',
  delivery_summary VARCHAR(512) DEFAULT NULL COMMENT '投递或抑制摘要',
  payload_json JSON DEFAULT NULL COMMENT '通知模拟或去重抑制证据的结构化载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  created_at DATETIME(3) NOT NULL COMMENT '创建时间戳',
  PRIMARY KEY (notification_log_id),
  KEY idx_alert_notification_tenant_alert_created (tenant_id, alert_id, created_at),
  KEY idx_alert_notification_tenant_dedupe_created (tenant_id, dedupe_key, created_at),
  KEY idx_alert_notification_tenant_status_created (tenant_id, delivery_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Simulated alert notification and dedupe suppression log';

CREATE TABLE IF NOT EXISTS governance_history_lookup_index (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  tenant_id VARCHAR(64) NOT NULL COMMENT '租户标识符',
  lookup_type VARCHAR(16) NOT NULL COMMENT '查询类别：TASK/REPORT',
  lookup_id VARCHAR(128) NOT NULL COMMENT '任务或报告标识符',
  trace_id VARCHAR(64) NOT NULL COMMENT '追踪标识符',
  source_target_type VARCHAR(64) NOT NULL COMMENT '原始审计目标类型',
  last_seen_at DATETIME NOT NULL COMMENT '最近审计事件时间',
  last_audit_id BIGINT UNSIGNED NOT NULL COMMENT '用于游标稳定性的最近审计日志 ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  UNIQUE KEY uk_governance_history_lookup_item (tenant_id, lookup_type, lookup_id, trace_id),
  KEY idx_governance_history_lookup_window (tenant_id, lookup_type, lookup_id, last_seen_at, last_audit_id),
  KEY idx_governance_history_lookup_trace (tenant_id, trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Materialized lookup index for long-window governance history reverse search';

INSERT INTO governance_history_lookup_index (
  tenant_id,
  lookup_type,
  lookup_id,
  trace_id,
  source_target_type,
  last_seen_at,
  last_audit_id,
  create_time,
  update_time
)
SELECT
  audit_log.tenant_id,
  CASE
    WHEN audit_log.target_type IN ('TASK', 'SQL_OPTIMIZATION_TASK', 'BENCHMARK_ENGINE_TASK', 'SQL_ACCELERATION_PLAN') THEN 'TASK'
    ELSE 'REPORT'
  END AS lookup_type,
  audit_log.target_id,
  audit_log.trace_id,
  MAX(audit_log.target_type) AS source_target_type,
  MAX(audit_log.create_time) AS last_seen_at,
  MAX(audit_log.id) AS last_audit_id,
  NOW(),
  NOW()
FROM audit_log
WHERE audit_log.trace_id IS NOT NULL
  AND audit_log.target_id IS NOT NULL
  AND audit_log.target_type IN ('TASK', 'SQL_OPTIMIZATION_TASK', 'BENCHMARK_ENGINE_TASK', 'SQL_ACCELERATION_PLAN', 'REPORT', 'BENCHMARK_ENGINE_REPORT')
GROUP BY audit_log.tenant_id,
  CASE
    WHEN audit_log.target_type IN ('TASK', 'SQL_OPTIMIZATION_TASK', 'BENCHMARK_ENGINE_TASK', 'SQL_ACCELERATION_PLAN') THEN 'TASK'
    ELSE 'REPORT'
  END,
  audit_log.target_id,
  audit_log.trace_id
ON DUPLICATE KEY UPDATE
  source_target_type = VALUES(source_target_type),
  last_seen_at = CASE
    WHEN VALUES(last_seen_at) > last_seen_at THEN VALUES(last_seen_at)
    ELSE last_seen_at
  END,
  last_audit_id = CASE
    WHEN VALUES(last_seen_at) > last_seen_at THEN VALUES(last_audit_id)
    WHEN VALUES(last_seen_at) = last_seen_at AND VALUES(last_audit_id) > last_audit_id THEN VALUES(last_audit_id)
    ELSE last_audit_id
  END,
  update_time = NOW();

DROP TRIGGER IF EXISTS trg_audit_log_lookup_index_ai;

DELIMITER $$
CREATE TRIGGER trg_audit_log_lookup_index_ai
AFTER INSERT ON audit_log
FOR EACH ROW
BEGIN
  IF NEW.trace_id IS NOT NULL
     AND NEW.target_id IS NOT NULL
     AND NEW.target_type IN ('TASK', 'SQL_OPTIMIZATION_TASK', 'BENCHMARK_ENGINE_TASK', 'SQL_ACCELERATION_PLAN', 'REPORT', 'BENCHMARK_ENGINE_REPORT') THEN
    INSERT INTO governance_history_lookup_index (
      tenant_id,
      lookup_type,
      lookup_id,
      trace_id,
      source_target_type,
      last_seen_at,
      last_audit_id
    ) VALUES (
      NEW.tenant_id,
      CASE
        WHEN NEW.target_type IN ('TASK', 'SQL_OPTIMIZATION_TASK', 'BENCHMARK_ENGINE_TASK', 'SQL_ACCELERATION_PLAN') THEN 'TASK'
        ELSE 'REPORT'
      END,
      NEW.target_id,
      NEW.trace_id,
      NEW.target_type,
      NEW.create_time,
      NEW.id
    )
    ON DUPLICATE KEY UPDATE
      source_target_type = VALUES(source_target_type),
      last_seen_at = CASE
        WHEN VALUES(last_seen_at) > last_seen_at THEN VALUES(last_seen_at)
        ELSE last_seen_at
      END,
      last_audit_id = CASE
        WHEN VALUES(last_seen_at) > last_seen_at THEN VALUES(last_audit_id)
        WHEN VALUES(last_seen_at) = last_seen_at AND VALUES(last_audit_id) > last_audit_id THEN VALUES(last_audit_id)
        ELSE last_audit_id
      END,
      update_time = NOW();
  END IF;
END$$
DELIMITER ;

CREATE TABLE IF NOT EXISTS business_logical_view (
  id VARCHAR(64) NOT NULL COMMENT '业务逻辑视图标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  view_code VARCHAR(128) NOT NULL COMMENT '稳定逻辑视图编码',
  view_name VARCHAR(255) NOT NULL COMMENT '逻辑视图显示名称',
  datasource_code VARCHAR(128) NOT NULL COMMENT '逻辑视图默认数据源',
  subject_area VARCHAR(128) DEFAULT NULL COMMENT '业务主题域',
  owner_user VARCHAR(128) DEFAULT NULL COMMENT '逻辑视图负责人',
  freshness_status VARCHAR(32) DEFAULT NULL COMMENT '最近新鲜度状态',
  sla_status VARCHAR(32) DEFAULT NULL COMMENT '最近 SLA 状态',
  queryable TINYINT(1) NOT NULL DEFAULT 1 COMMENT '逻辑视图是否可查询',
  latest_refresh_time DATETIME DEFAULT NULL COMMENT '最近成功刷新时间戳',
  description TEXT DEFAULT NULL COMMENT '逻辑视图描述',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  UNIQUE KEY uk_business_logical_view_tenant_code (tenant_id, view_code),
  KEY idx_business_logical_view_tenant_datasource (tenant_id, datasource_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Business logical view catalog';

CREATE TABLE IF NOT EXISTS logical_object_mapping (
  id VARCHAR(64) NOT NULL COMMENT '逻辑对象映射标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  logical_view_id VARCHAR(64) NOT NULL COMMENT '业务逻辑视图标识符',
  target_object_type VARCHAR(32) NOT NULL COMMENT '映射对象类型',
  target_object_key VARCHAR(255) NOT NULL COMMENT '规范映射对象键',
  target_object_name VARCHAR(255) NOT NULL COMMENT '映射对象显示名称',
  mapping_role VARCHAR(64) DEFAULT NULL COMMENT '映射角色，例如 SOURCE 或 SERVING',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  KEY idx_logical_object_mapping_view (tenant_id, logical_view_id),
  KEY idx_logical_object_mapping_target (tenant_id, target_object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Business logical view to physical object mapping';

CREATE TABLE IF NOT EXISTS database_view_ref (
  id VARCHAR(64) NOT NULL COMMENT '数据库视图标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) NOT NULL COMMENT '数据源编码',
  view_name VARCHAR(255) NOT NULL COMMENT '数据库视图名称',
  object_key VARCHAR(255) NOT NULL COMMENT '规范数据库视图对象键',
  schema_name VARCHAR(128) DEFAULT NULL COMMENT 'Schema 名称',
  catalog_name VARCHAR(128) DEFAULT NULL COMMENT 'Catalog 名称',
  owner_user VARCHAR(128) DEFAULT NULL COMMENT '数据库视图负责人',
  queryable TINYINT(1) NOT NULL DEFAULT 1 COMMENT '数据库视图是否可查询',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  UNIQUE KEY uk_database_view_ref_lookup (tenant_id, datasource_code, view_name),
  KEY idx_database_view_ref_key (tenant_id, object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Database view catalog';

CREATE TABLE IF NOT EXISTS database_view_dependency (
  id VARCHAR(64) NOT NULL COMMENT '数据库视图依赖标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  db_view_id VARCHAR(64) NOT NULL COMMENT '数据库视图标识符',
  dependency_object_type VARCHAR(32) NOT NULL COMMENT '依赖对象类型',
  dependency_object_key VARCHAR(255) NOT NULL COMMENT '依赖对象键',
  dependency_object_name VARCHAR(255) NOT NULL COMMENT '依赖对象名称',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  KEY idx_database_view_dependency_view (tenant_id, db_view_id),
  KEY idx_database_view_dependency_key (tenant_id, dependency_object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Database view dependency catalog';

CREATE TABLE IF NOT EXISTS metadata_snapshot (
  snapshot_id VARCHAR(64) NOT NULL COMMENT '元数据快照标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码',
  object_type VARCHAR(32) NOT NULL COMMENT '对象类型：LOGICAL_VIEW/DB_VIEW/TABLE 等',
  object_key VARCHAR(255) NOT NULL COMMENT '规范对象键',
  object_name VARCHAR(255) DEFAULT NULL COMMENT '对象显示名称',
  catalog_name VARCHAR(128) DEFAULT NULL COMMENT 'Catalog 名称',
  schema_name VARCHAR(128) DEFAULT NULL COMMENT 'Schema 名称',
  freshness_status VARCHAR(32) DEFAULT NULL COMMENT '新鲜度状态',
  sla_status VARCHAR(32) DEFAULT NULL COMMENT 'SLA 状态',
  queryability_status VARCHAR(32) DEFAULT NULL COMMENT '可查询状态',
  evidence_status VARCHAR(32) DEFAULT NULL COMMENT '证据采集状态',
  latest_refresh_time DATETIME DEFAULT NULL COMMENT '最近刷新时间',
  expected_sla_time DATETIME DEFAULT NULL COMMENT '预期 SLA 时间',
  snapshot_time DATETIME DEFAULT NULL COMMENT '快照采集时间',
  evidence_source VARCHAR(64) DEFAULT NULL COMMENT '证据来源',
  column_count INT DEFAULT NULL COMMENT '字段数量',
  partition_count INT DEFAULT NULL COMMENT '分区数量',
  row_count BIGINT DEFAULT NULL COMMENT '行数估计',
  storage_bytes BIGINT DEFAULT NULL COMMENT '存储字节数估计',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  execution_id VARCHAR(64) DEFAULT NULL COMMENT '执行标识符',
  history_id VARCHAR(128) DEFAULT NULL COMMENT '查询或解析历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '解析任务标识符',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联报表编码',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  upstream_refs_json JSON DEFAULT NULL COMMENT '上游血缘引用快照',
  downstream_refs_json JSON DEFAULT NULL COMMENT '下游血缘引用快照',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (snapshot_id),
  UNIQUE KEY uk_metadata_snapshot_tenant_object (tenant_id, object_key),
  KEY idx_metadata_snapshot_tenant_type_time (tenant_id, object_type, snapshot_time),
  KEY idx_metadata_snapshot_datasource_time (tenant_id, datasource_code, snapshot_time),
  KEY idx_metadata_snapshot_status (tenant_id, freshness_status, sla_status, queryability_status, evidence_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance metadata snapshot catalog';

CREATE TABLE IF NOT EXISTS metadata_column_snapshot (
  column_snapshot_id VARCHAR(64) NOT NULL COMMENT '字段级元数据快照标识符',
  snapshot_id VARCHAR(64) NOT NULL COMMENT '关联 metadata_snapshot 标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码',
  object_type VARCHAR(32) NOT NULL COMMENT '对象类型：DB_VIEW/TABLE/LOGICAL_VIEW 等',
  object_key VARCHAR(255) NOT NULL COMMENT '规范对象键',
  column_name VARCHAR(255) NOT NULL COMMENT '字段名称',
  column_ordinal INT DEFAULT NULL COMMENT '字段序号',
  data_type VARCHAR(128) DEFAULT NULL COMMENT '字段类型',
  nullable_flag TINYINT(1) DEFAULT NULL COMMENT '是否可空',
  primary_key_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否主键或唯一键证据',
  partition_key_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否分区字段证据',
  expression_text TEXT DEFAULT NULL COMMENT '视图字段表达式或派生字段定义',
  source_column_refs_json JSON DEFAULT NULL COMMENT '展开后的来源字段引用快照',
  evidence_source VARCHAR(64) DEFAULT NULL COMMENT '证据来源',
  snapshot_time DATETIME DEFAULT NULL COMMENT '字段快照采集时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (column_snapshot_id),
  UNIQUE KEY uk_metadata_column_snapshot_object_column (tenant_id, object_key, column_name),
  KEY idx_metadata_column_snapshot_parent (tenant_id, snapshot_id),
  KEY idx_metadata_column_snapshot_object (tenant_id, object_key, column_ordinal),
  KEY idx_metadata_column_snapshot_datasource_time (tenant_id, datasource_code, snapshot_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance field-level metadata snapshot catalog';

CREATE TABLE IF NOT EXISTS sql_parse_history (
  parse_history_id VARCHAR(128) NOT NULL COMMENT 'sql-optimization 持有的 SQL 解析历史标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '解析来源，例如 STRUCTURE_PARSE/COMBINED_PARSE/PARSE_BATCH/REPORT_BATCH/END_OF_DAY_SLOW_SQL',
  source_id VARCHAR(128) DEFAULT NULL COMMENT '来源条目或执行历史标识符',
  batch_key VARCHAR(255) DEFAULT NULL COMMENT '定时解析作业的幂等批次键',
  parse_task_id VARCHAR(64) NOT NULL COMMENT '结构或组合解析任务标识符',
  sql_fingerprint CHAR(32) NOT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源业务标识符或别名',
  datasource_type VARCHAR(32) DEFAULT NULL COMMENT '数据源类型',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的报表编码',
  stage_code VARCHAR(32) DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的执行阶段',
  biz_date VARCHAR(32) DEFAULT NULL COMMENT '从 SQL 注释上下文解析出的业务日期',
  query_date_start VARCHAR(32) DEFAULT NULL COMMENT '从 SQL 正文解析出的查询日期下界',
  query_date_end VARCHAR(32) DEFAULT NULL COMMENT '从 SQL 正文解析出的查询日期上界',
  query_date_status VARCHAR(32) DEFAULT NULL COMMENT '查询日期提取状态，例如 RESOLVED/UNRESOLVED/PARTIAL',
  access_channel VARCHAR(32) DEFAULT NULL COMMENT '解析访问渠道或批次来源',
  parser_mode VARCHAR(32) DEFAULT NULL COMMENT 'SQL 解析器模式：APACHE_CALCITE 或 APACHE_CALCITE_WITH_PLAN',
  sql_text MEDIUMTEXT NOT NULL COMMENT '解析管理捕获的 SQL 文本',
  sql_template_text MEDIUMTEXT DEFAULT NULL COMMENT '预备 SQL 模板文本',
  binding_mode VARCHAR(32) DEFAULT NULL COMMENT 'Binding 模式，例如 POSITIONAL/NAMED',
  parameterized_sql_flag TINYINT(1) DEFAULT NULL COMMENT '绑定前 SQL 是否已参数化',
  result_status VARCHAR(32) NOT NULL COMMENT '解析结果状态，例如 SUCCESS/PARTIAL/FAILED',
  target_engine VARCHAR(32) DEFAULT NULL COMMENT '解析流程确定的目标引擎',
  structure_parse_summary_json JSON DEFAULT NULL COMMENT '结构解析摘要载荷',
  access_parse_summary_json JSON DEFAULT NULL COMMENT '访问解析摘要载荷',
  result_summary_json JSON DEFAULT NULL COMMENT '组合解析结果摘要载荷',
  result_payload_json JSON DEFAULT NULL COMMENT '完整解析结果载荷',
  query_context_json JSON DEFAULT NULL COMMENT '用于解析管理的结构化查询上下文',
  comment_context_json JSON DEFAULT NULL COMMENT '结构化 SQL 注释上下文 JSON',
  binding_summary_json JSON DEFAULT NULL COMMENT '结构化参数绑定摘要 JSON',
  logical_object_hits_json JSON DEFAULT NULL COMMENT '结构化逻辑对象命中摘要 JSON',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景摘要载荷',
  logical_object_keys_json JSON DEFAULT NULL COMMENT '逻辑对象键摘要载荷',
  trace_id VARCHAR(64) DEFAULT NULL COMMENT '追踪标识符',
  request_id VARCHAR(64) DEFAULT NULL COMMENT '请求标识符',
  saga_id VARCHAR(128) DEFAULT NULL COMMENT '跨服务补偿链 Saga 标识符',
  submitted_by VARCHAR(64) DEFAULT NULL COMMENT '操作人标识符',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间戳',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (parse_history_id),
  KEY idx_sql_parse_history_tenant_time (tenant_id, submitted_at),
  KEY idx_sql_parse_history_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_sql_parse_history_source (tenant_id, source_type, source_id),
  KEY idx_sql_parse_history_batch (tenant_id, batch_key, sql_fingerprint),
  KEY idx_sql_parse_history_report_stage_date (tenant_id, report_code, stage_code, biz_date),
  KEY idx_sql_parse_history_datasource (tenant_id, datasource_code, submitted_at),
  KEY idx_sql_parse_history_trace (trace_id, request_id),
  KEY idx_sql_parse_history_status (tenant_id, result_status, submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Independent SQL parse history records owned by sql-optimization';

CREATE TABLE IF NOT EXISTS parse_batch (
  batch_id VARCHAR(64) NOT NULL COMMENT '解析批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  batch_name VARCHAR(255) NOT NULL COMMENT '批次显示名称',
  import_mode VARCHAR(32) NOT NULL COMMENT '导入模式，例如 SQL_FILE/TABULAR_FILE/REPORT_CATALOG',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型，例如 FILE_UPLOAD/REPORT_CATALOG_IMPORT',
  file_type VARCHAR(16) NOT NULL COMMENT '上传文件类型',
  template_version VARCHAR(32) DEFAULT NULL COMMENT '模板版本',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码覆盖值',
  parser_mode VARCHAR(32) NOT NULL DEFAULT 'APACHE_CALCITE' COMMENT 'SQL 解析器模式：APACHE_CALCITE 或 APACHE_CALCITE_WITH_PLAN',
  structure_parse_only TINYINT(1) NOT NULL DEFAULT 0 COMMENT '批次是否仅运行结构解析',
  status VARCHAR(32) NOT NULL COMMENT '当前批次状态',
  total_records INT NOT NULL DEFAULT 0 COMMENT '导入记录数',
  success_records INT NOT NULL DEFAULT 0 COMMENT '成功记录数',
  partial_success_records INT NOT NULL DEFAULT 0 COMMENT '部分成功记录数',
  failed_records INT NOT NULL DEFAULT 0 COMMENT '失败记录数',
  structure_parse_success_rate DECIMAL(6,2) DEFAULT NULL COMMENT '结构解析成功率百分比',
  access_parse_success_rate DECIMAL(6,2) DEFAULT NULL COMMENT '访问解析成功率百分比',
  status_history_json JSON NOT NULL COMMENT '批次状态历史载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '批次创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id),
  KEY idx_parse_batch_tenant_status_created (tenant_id, status, created_at),
  KEY idx_parse_batch_tenant_mode (tenant_id, import_mode, file_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bulk parse batch contract baseline';

CREATE TABLE IF NOT EXISTS parse_batch_item (
  item_id VARCHAR(64) NOT NULL COMMENT '解析批次条目标识符',
  batch_id VARCHAR(64) NOT NULL COMMENT '所属解析批次标识符',
  sequence_number INT NOT NULL COMMENT '上传批次内从 1 开始的序号',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '带入治理上下文的可选报表编码',
  report_name VARCHAR(255) DEFAULT NULL COMMENT '可选报表显示名称',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '该行解析得到的数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据，例如 DEV/UAT/PROD',
  biz_date VARCHAR(32) DEFAULT NULL COMMENT '执行日期元数据',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  owner VARCHAR(128) DEFAULT NULL COMMENT '负责人元数据',
  tags VARCHAR(255) DEFAULT NULL COMMENT '自由格式标签',
  sql_text MEDIUMTEXT NOT NULL COMMENT '解析后的 SQL 文本',
  sql_template_text MEDIUMTEXT DEFAULT NULL COMMENT '预备 SQL 模板文本',
  bind_parameters_json JSON DEFAULT NULL COMMENT '脱敏后的绑定参数载荷',
  binding_mode VARCHAR(32) DEFAULT NULL COMMENT 'Binding 模式，例如 POSITIONAL/NAMED',
  status VARCHAR(32) NOT NULL COMMENT '终态条目状态',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '结构/访问解析任务标识符',
  structure_syntax_status VARCHAR(32) DEFAULT NULL COMMENT '结构解析语法状态',
  access_service_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析提供方状态',
  access_connection_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析连接状态',
  plan_analysis_status VARCHAR(32) DEFAULT NULL COMMENT 'Hetu EXPLAIN 计划分析状态',
  combined_analysis_status VARCHAR(32) DEFAULT NULL COMMENT '结构与计划联合分析状态',
  plan_analysis_json JSON DEFAULT NULL COMMENT 'Hetu EXPLAIN 计划分析摘要载荷',
  failure_reason VARCHAR(128) DEFAULT NULL COMMENT '失败或降级原因',
  history_id VARCHAR(128) DEFAULT NULL COMMENT '该已解析 SQL 的 SQL 解析历史 ID',
  history_persisted TINYINT(1) DEFAULT NULL COMMENT '该 SQL 是否已持久化 SQL 解析历史',
  history_persistence_status VARCHAR(32) DEFAULT NULL COMMENT '历史写入状态，例如 SAVED、NO_RESPONSE、WRITE_FAILED 或 WRITE_SKIPPED',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景摘要载荷',
  logical_object_keys_json JSON DEFAULT NULL COMMENT '逻辑对象命中摘要载荷',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (item_id),
  KEY idx_parse_batch_item_batch_seq (batch_id, sequence_number),
  KEY idx_parse_batch_item_batch_status (batch_id, status),
  KEY idx_parse_batch_item_report (batch_id, report_code),
  KEY idx_parse_batch_item_history (history_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bulk parse batch imported records and parse evidence';

CREATE TABLE IF NOT EXISTS report_batch (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表目录批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  batch_name VARCHAR(255) NOT NULL COMMENT '批次显示名称',
  file_type VARCHAR(16) NOT NULL COMMENT '来源文件类型，模拟来源当前为 TXT',
  report_code_field VARCHAR(128) NOT NULL COMMENT '包含 report_code 的列名',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码覆盖值',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据，例如 DEV/UAT/PROD',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  parser_mode VARCHAR(32) NOT NULL DEFAULT 'APACHE_CALCITE' COMMENT 'SQL 解析器模式：APACHE_CALCITE 或 APACHE_CALCITE_WITH_PLAN',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型，例如 TXT_MOCK_SOURCE',
  status VARCHAR(32) NOT NULL COMMENT '当前批次状态',
  total_reports INT NOT NULL DEFAULT 0 COMMENT '导入报表数',
  resolved_reports INT NOT NULL DEFAULT 0 COMMENT '已解析报表数',
  failed_reports INT NOT NULL DEFAULT 0 COMMENT '失败报表数',
  status_history_json JSON NOT NULL COMMENT '批次状态历史载荷',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '批次创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id),
  KEY idx_report_batch_tenant_status_created (tenant_id, status, created_at),
  KEY idx_report_batch_tenant_code (tenant_id, report_code_field)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog batch baseline';

CREATE TABLE IF NOT EXISTS report_batch_item (
  item_id VARCHAR(64) NOT NULL COMMENT '报表批次条目标识符',
  batch_id VARCHAR(64) NOT NULL COMMENT '所属报表批次标识符',
  sequence_number INT NOT NULL COMMENT '上传批次内从 1 开始的序号',
  report_code VARCHAR(128) NOT NULL COMMENT '报表编码',
  report_name VARCHAR(255) DEFAULT NULL COMMENT '报表名称',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '该行解析得到的数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据',
  priority VARCHAR(32) DEFAULT NULL COMMENT '优先级提示',
  source_file_line VARCHAR(4096) DEFAULT NULL COMMENT '源行、源列和报表编码定位摘要',
  sql_column_name VARCHAR(128) DEFAULT NULL COMMENT '提供该 SQL 的来源电子表格列',
  sql_ordinal_in_report INT DEFAULT NULL COMMENT '同一 report_code 内从 1 开始的 SQL 序号',
  sql_text MEDIUMTEXT DEFAULT NULL COMMENT '解析后的 SQL 文本',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '解析任务标识符',
  structure_syntax_status VARCHAR(32) DEFAULT NULL COMMENT '结构解析语法状态',
  access_service_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析提供方状态',
  access_connection_status VARCHAR(32) DEFAULT NULL COMMENT '访问解析连接状态',
  plan_analysis_status VARCHAR(32) DEFAULT NULL COMMENT 'Hetu EXPLAIN 计划分析状态',
  combined_analysis_status VARCHAR(32) DEFAULT NULL COMMENT '结构与计划联合分析状态',
  plan_analysis_json JSON DEFAULT NULL COMMENT 'Hetu EXPLAIN 计划分析摘要载荷',
  failure_reason VARCHAR(128) DEFAULT NULL COMMENT '失败或降级原因',
  history_id VARCHAR(128) DEFAULT NULL COMMENT '该已解析报表 SQL 的 SQL 解析历史 ID',
  history_persisted TINYINT(1) DEFAULT NULL COMMENT '该 SQL 是否已持久化 SQL 解析历史',
  history_persistence_status VARCHAR(32) DEFAULT NULL COMMENT '历史写入状态，例如 SAVED、NO_RESPONSE、WRITE_FAILED 或 WRITE_SKIPPED',
  status VARCHAR(32) NOT NULL COMMENT '当前条目状态',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景摘要载荷',
  logical_object_keys_json JSON DEFAULT NULL COMMENT '逻辑对象命中摘要载荷',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (item_id),
  KEY idx_report_batch_item_batch_seq (batch_id, sequence_number),
  KEY idx_report_batch_item_batch_status (batch_id, status),
  KEY idx_report_batch_item_report (batch_id, report_code),
  KEY idx_report_batch_item_report_sql (batch_id, report_code, sql_ordinal_in_report),
  KEY idx_report_batch_item_history (history_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report catalog imported records and parse evidence';

CREATE TABLE IF NOT EXISTS report_batch_stat_summary (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  total_sql_count INT NOT NULL DEFAULT 0 COMMENT '批次 SQL 总数',
  resolved_sql_count INT NOT NULL DEFAULT 0 COMMENT '完全解析 SQL 数',
  partial_resolved_sql_count INT NOT NULL DEFAULT 0 COMMENT '部分解析 SQL 数',
  failed_sql_count INT NOT NULL DEFAULT 0 COMMENT '解析失败 SQL 数',
  issue_sql_count INT NOT NULL DEFAULT 0 COMMENT '存在问题场景的 SQL 数',
  total_issue_count INT NOT NULL DEFAULT 0 COMMENT '问题场景出现总次数',
  issue_scene_count INT NOT NULL DEFAULT 0 COMMENT '不同问题场景数',
  important_sql_count INT NOT NULL DEFAULT 0 COMMENT '重要问题 SQL 数',
  urgent_sql_count INT NOT NULL DEFAULT 0 COMMENT '紧急问题 SQL 数',
  merge_candidate_report_count INT NOT NULL DEFAULT 0 COMMENT '可合并候选报表数',
  plan_analysis_success_count INT NOT NULL DEFAULT 0 COMMENT '计划分析成功 SQL 数',
  plan_analysis_partial_count INT NOT NULL DEFAULT 0 COMMENT '计划分析部分或跳过 SQL 数',
  plan_analysis_failed_count INT NOT NULL DEFAULT 0 COMMENT '计划分析失败 SQL 数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id),
  KEY idx_report_batch_stat_summary_batch (batch_id, updated_at),
  KEY idx_report_batch_stat_summary_tenant (tenant_id, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch normalized statistics summary';

CREATE TABLE IF NOT EXISTS report_batch_issue_scene_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  issue_scene VARCHAR(128) NOT NULL COMMENT '问题场景编码',
  issue_domain VARCHAR(64) DEFAULT NULL COMMENT '问题领域',
  severity VARCHAR(32) DEFAULT NULL COMMENT '严重级别',
  priority_level VARCHAR(16) DEFAULT NULL COMMENT '优先级等级',
  priority_score INT NOT NULL DEFAULT 0 COMMENT '优先级分值',
  affected_sql_count INT NOT NULL DEFAULT 0 COMMENT '受影响 SQL 数',
  affected_issue_count INT NOT NULL DEFAULT 0 COMMENT '受影响问题次数',
  sql_ratio DECIMAL(12,8) NOT NULL DEFAULT 0 COMMENT '受影响 SQL 占比',
  important TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重要',
  urgent TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否紧急',
  report_count INT NOT NULL DEFAULT 0 COMMENT '受影响报表数',
  logical_object_count INT NOT NULL DEFAULT 0 COMMENT '受影响逻辑对象数',
  sample_report_codes_json JSON DEFAULT NULL COMMENT '样例报表编码列表',
  sample_logical_object_keys_json JSON DEFAULT NULL COMMENT '样例逻辑对象键列表',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, issue_scene),
  KEY idx_report_batch_issue_scene_batch (batch_id, affected_sql_count),
  KEY idx_report_batch_issue_scene_tenant (tenant_id, issue_scene)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch issue scene statistics';

CREATE TABLE IF NOT EXISTS report_batch_severity_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  severity VARCHAR(32) NOT NULL COMMENT '严重级别',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, severity),
  KEY idx_report_batch_severity_batch (batch_id, severity),
  KEY idx_report_batch_severity_tenant (tenant_id, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch severity distribution';

CREATE TABLE IF NOT EXISTS report_batch_report_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  report_code VARCHAR(128) NOT NULL COMMENT '报表编码',
  sql_count INT NOT NULL DEFAULT 0 COMMENT '报表 SQL 数',
  issue_sql_count INT NOT NULL DEFAULT 0 COMMENT '存在问题 SQL 数',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  issue_sql_ratio DECIMAL(12,8) NOT NULL DEFAULT 0 COMMENT '问题 SQL 占比',
  highest_priority_level VARCHAR(16) DEFAULT NULL COMMENT '最高优先级等级',
  highest_priority_score INT NOT NULL DEFAULT 0 COMMENT '最高优先级分值',
  important TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重要',
  urgent TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否紧急',
  issue_scenes_json JSON DEFAULT NULL COMMENT '问题场景列表',
  merge_candidate TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否合并候选',
  merge_candidate_sql_count INT NOT NULL DEFAULT 0 COMMENT '合并候选 SQL 数',
  merge_candidate_reason VARCHAR(512) DEFAULT NULL COMMENT '合并候选原因',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, report_code),
  KEY idx_report_batch_report_batch (batch_id, issue_sql_count),
  KEY idx_report_batch_report_tenant (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch report-level statistics';

CREATE TABLE IF NOT EXISTS report_batch_sql_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  item_id VARCHAR(64) NOT NULL COMMENT '报表批次条目标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '解析任务标识符',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '报表编码',
  report_name VARCHAR(255) DEFAULT NULL COMMENT '报表名称',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '阶段元数据',
  sql_column_name VARCHAR(128) DEFAULT NULL COMMENT 'SQL 来源列名',
  sql_ordinal_in_report INT DEFAULT NULL COMMENT '同一报表内 SQL 序号',
  status VARCHAR(32) DEFAULT NULL COMMENT '条目解析状态',
  sql_digest VARCHAR(255) DEFAULT NULL COMMENT 'SQL 摘要',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  highest_priority_level VARCHAR(16) DEFAULT NULL COMMENT '最高优先级等级',
  highest_priority_score INT NOT NULL DEFAULT 0 COMMENT '最高优先级分值',
  important TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否重要',
  urgent TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否紧急',
  issue_locations_json JSON DEFAULT NULL COMMENT '问题定位列表',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, item_id),
  KEY idx_report_batch_sql_batch_priority (batch_id, highest_priority_score, issue_count),
  KEY idx_report_batch_sql_batch_report (batch_id, report_code),
  KEY idx_report_batch_sql_tenant (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch SQL-level statistics';

CREATE TABLE IF NOT EXISTS report_batch_sql_issue_scene_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  item_id VARCHAR(64) NOT NULL COMMENT '报表批次条目标识符',
  issue_scene VARCHAR(128) NOT NULL COMMENT '问题场景编码',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  PRIMARY KEY (batch_id, item_id, issue_scene),
  KEY idx_report_batch_sql_issue_scene_batch (batch_id, issue_scene),
  KEY idx_report_batch_sql_issue_scene_tenant (tenant_id, issue_scene)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch SQL issue scene membership';

CREATE TABLE IF NOT EXISTS report_batch_sql_logical_object_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  item_id VARCHAR(64) NOT NULL COMMENT '报表批次条目标识符',
  logical_object_key VARCHAR(255) NOT NULL COMMENT '逻辑对象键',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  PRIMARY KEY (batch_id, item_id, logical_object_key),
  KEY idx_report_batch_sql_logical_object_batch (batch_id, logical_object_key),
  KEY idx_report_batch_sql_logical_object_tenant (tenant_id, logical_object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch SQL logical object membership';

CREATE TABLE IF NOT EXISTS report_batch_priority_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  priority_level VARCHAR(16) NOT NULL COMMENT '优先级等级',
  urgency_bucket VARCHAR(32) NOT NULL COMMENT '重要紧急桶',
  sql_count INT NOT NULL DEFAULT 0 COMMENT 'SQL 数',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  report_count INT NOT NULL DEFAULT 0 COMMENT '报表数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, priority_level, urgency_bucket),
  KEY idx_report_batch_priority_batch (batch_id, priority_level),
  KEY idx_report_batch_priority_tenant (tenant_id, priority_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch priority matrix statistics';

CREATE TABLE IF NOT EXISTS report_batch_importance_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  importance_bucket VARCHAR(32) NOT NULL COMMENT '重要紧急桶',
  sql_count INT NOT NULL DEFAULT 0 COMMENT 'SQL 数',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  report_count INT NOT NULL DEFAULT 0 COMMENT '报表数',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, importance_bucket),
  KEY idx_report_batch_importance_batch (batch_id, sql_count),
  KEY idx_report_batch_importance_tenant (tenant_id, importance_bucket)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch importance bucket statistics';

CREATE TABLE IF NOT EXISTS report_batch_logical_object_stat (
  batch_id VARCHAR(64) NOT NULL COMMENT '报表批次标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  logical_object_key VARCHAR(255) NOT NULL COMMENT '逻辑对象键',
  sql_count INT NOT NULL DEFAULT 0 COMMENT 'SQL 数',
  issue_count INT NOT NULL DEFAULT 0 COMMENT '问题次数',
  report_count INT NOT NULL DEFAULT 0 COMMENT '报表数',
  report_codes_json JSON DEFAULT NULL COMMENT '关联报表编码列表',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (batch_id, logical_object_key),
  KEY idx_report_batch_logical_object_batch (batch_id, sql_count),
  KEY idx_report_batch_logical_object_tenant (tenant_id, logical_object_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report batch logical object statistics';

CREATE TABLE IF NOT EXISTS acceleration_recommendation (
  recommendation_id VARCHAR(64) NOT NULL COMMENT '推荐标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_type VARCHAR(32) NOT NULL COMMENT '推荐类型：REWRITE/ACCELERATION/CREATE_TABLE/PREWARM/MAINTENANCE',
  source_sql_id VARCHAR(64) DEFAULT NULL COMMENT '来源 SQL、解析条目、历史或任务标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联查询历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse task标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse/报表批次标识符',
  route_decision_id VARCHAR(64) DEFAULT NULL COMMENT '关联路由决策标识符',
  alert_id VARCHAR(64) DEFAULT NULL COMMENT '关联告警标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  source_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '原始 SQL 文本或模板',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '推荐 SQL、建表 SQL、预热 SQL 或维护 SQL',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '目标执行引擎',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT '目标数据源编码',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  summary VARCHAR(512) DEFAULT NULL COMMENT '推荐摘要',
  reason TEXT DEFAULT NULL COMMENT '推荐原因',
  expected_gain VARCHAR(512) DEFAULT NULL COMMENT '预期收益描述',
  benefit_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '收益级别：UNKNOWN/LOW/MEDIUM/HIGH',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '风险级别：UNKNOWN/LOW/MEDIUM/HIGH/CRITICAL',
  risk_summary TEXT DEFAULT NULL COMMENT '风险摘要与约束',
  requires_dispatch TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示需要外部装载/分发协同',
  status VARCHAR(32) NOT NULL DEFAULT 'RECOMMENDED' COMMENT '推荐状态：RECOMMENDED/REVIEWING/DISPATCH_READY/CANCELLED；SQLForge 内无已执行状态',
  source_type VARCHAR(32) DEFAULT NULL COMMENT '用于推荐可追踪性的 PARSE/QUERY 来源类型',
  source_kind VARCHAR(64) DEFAULT NULL COMMENT '治理来源类型，例如 STRUCTURE_PARSE/QUERY_HISTORY',
  source_id VARCHAR(128) DEFAULT NULL COMMENT '与来源类型/种类配对的规范来源标识符',
  evidence_level VARCHAR(32) DEFAULT NULL COMMENT '证据level：STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED',
  schema_version VARCHAR(64) NOT NULL DEFAULT 'SQL_RECOMMENDATION_RULE_MODEL_V1' COMMENT '推荐规则输出模式版本',
  rule_chain_json JSON DEFAULT NULL COMMENT '已应用或已选择的推荐规则链证据',
  unapplied_rules_json JSON DEFAULT NULL COMMENT '已考虑但未应用的规则及原因证据',
  preconditions_json JSON DEFAULT NULL COMMENT '校验或后续应用前所需的前置条件',
  semantic_risks_json JSON DEFAULT NULL COMMENT '需要校验或人工评审的语义风险',
  acceleration_artifact_json JSON DEFAULT NULL COMMENT '高级 MV accelerationArtifact 持久快照，响应仅返回允许的高级 MV 类型',
  expected_benefit_json JSON DEFAULT NULL COMMENT '静态预估收益证据，非真实执行收益',
  estimated_cost_json JSON DEFAULT NULL COMMENT '静态预估成本与治理跟进证据',
  confidence INT DEFAULT NULL COMMENT '静态模型置信分 0-100',
  validation_method VARCHAR(64) DEFAULT NULL COMMENT '批准或后续应用前要求的校验方法',
  validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT '校验状态：NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '校验后是否允许后续自动应用',
  manual_review_required TINYINT(1) NOT NULL DEFAULT 1 COMMENT '推荐是否需要人工评审',
  source_problems_json JSON DEFAULT NULL COMMENT '改写试算来源问题证据，不代表生产已改写',
  issue_rule_links_json JSON DEFAULT NULL COMMENT '来源问题到改写规则的试算链路证据',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '推荐创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (recommendation_id),
  KEY idx_acc_reco_tenant_type_created (tenant_id, recommendation_type, created_at),
  KEY idx_acc_reco_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_reco_sql_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_reco_report_code (tenant_id, report_code),
  KEY idx_acc_reco_history (tenant_id, history_id),
  KEY idx_acc_reco_parse_task (tenant_id, parse_task_id),
  KEY idx_acc_reco_batch (tenant_id, batch_id),
  KEY idx_acc_reco_route (tenant_id, route_decision_id),
  KEY idx_acc_reco_alert (tenant_id, alert_id),
  KEY idx_acc_reco_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_acc_reco_validation (tenant_id, validation_status, manual_review_required)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Read-only SQL acceleration and rewrite recommendation catalog';

CREATE TABLE IF NOT EXISTS rewrite_trial_run (
  run_id VARCHAR(64) NOT NULL COMMENT '改写试算 run 标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  source_kind VARCHAR(64) DEFAULT NULL COMMENT '试算来源类型，例如 STRUCTURE_PARSE/PARSE_BATCH/QUERY_HISTORY/MANUAL',
  source_id VARCHAR(128) DEFAULT NULL COMMENT '来源对象标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '批量解析来源批次标识符',
  status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED' COMMENT '试算状态，不代表生产改写事实',
  total_count INT NOT NULL DEFAULT 0 COMMENT '本次试算总条目数',
  accepted_count INT NOT NULL DEFAULT 0 COMMENT '已接受进入试算的条目数',
  skipped_count INT NOT NULL DEFAULT 0 COMMENT '因无来源问题或解析无效而跳过的条目数',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '发起人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (run_id),
  KEY idx_rewrite_trial_run_tenant_created (tenant_id, created_at),
  KEY idx_rewrite_trial_run_batch_created (tenant_id, batch_id, created_at),
  KEY idx_rewrite_trial_run_source (tenant_id, source_kind, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Issue-driven SQL rewrite trial run, not production rewrite history';

CREATE TABLE IF NOT EXISTS rewrite_trial_item (
  trial_item_id VARCHAR(64) NOT NULL COMMENT '改写试算条目标识符',
  run_id VARCHAR(64) NOT NULL COMMENT '所属 rewrite_trial_run 标识符',
  batch_item_id VARCHAR(64) DEFAULT NULL COMMENT '关联解析批次条目标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联结构解析任务标识符',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT '关联解析历史标识符',
  history_id VARCHAR(128) DEFAULT NULL COMMENT '关联 SQL 历史或解析历史标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '关联数据源编码',
  source_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '试算来源 SQL 文本',
  source_problems_json JSON DEFAULT NULL COMMENT '来源问题证据，含 issueScene/severity/evidenceRef',
  task_id VARCHAR(64) DEFAULT NULL COMMENT '关联优化任务标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联推荐标识符',
  rewrite_record_id VARCHAR(64) DEFAULT NULL COMMENT '用户采纳后关联改写记录标识符',
  trial_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED' COMMENT '试算状态，不得混同 rewriteApplied',
  failure_reason VARCHAR(512) DEFAULT NULL COMMENT '失败或跳过原因',
  candidate_sql MEDIUMTEXT DEFAULT NULL COMMENT '试算生成的候选 SQL，未发布',
  validation_status VARCHAR(32) DEFAULT NULL COMMENT '关联验证状态',
  issue_rule_links_json JSON DEFAULT NULL COMMENT '来源问题到改写规则链路证据',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (trial_item_id),
  KEY idx_rewrite_trial_item_run (run_id),
  KEY idx_rewrite_trial_item_batch_item (batch_item_id),
  KEY idx_rewrite_trial_item_parse_task (parse_task_id),
  KEY idx_rewrite_trial_item_history (history_id),
  KEY idx_rewrite_trial_item_recommendation (recommendation_id),
  KEY idx_rewrite_trial_item_fingerprint (sql_fingerprint),
  KEY idx_rewrite_trial_item_status (trial_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Issue-driven SQL rewrite trial item, candidate only';

CREATE TABLE IF NOT EXISTS acceleration_candidate (
  candidate_id VARCHAR(64) NOT NULL COMMENT '加速候选标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '来源族：PARSE/QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '归一化来源类型',
  source_id VARCHAR(128) NOT NULL COMMENT '来源对象标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT '关联sql_parse_历史标识符',
  parse_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse task标识符',
  batch_id VARCHAR(64) DEFAULT NULL COMMENT '关联parse/报表批次标识符',
  batch_item_id VARCHAR(64) DEFAULT NULL COMMENT '关联解析/报表批次条目标识符',
  benchmark_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联压测 task标识符',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联optimization task标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '关联数据源编码',
  stage VARCHAR(32) DEFAULT NULL COMMENT '来源环境或生命周期阶段',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  candidate_type VARCHAR(32) NOT NULL DEFAULT 'ACCELERATION_AND_REWRITE' COMMENT '候选类型：ACCELERATION/REWRITE/ACCELERATION_AND_REWRITE',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '候选状态：DRAFT/RECOMMENDED/PLAN_CREATED/REJECTED/INVALID/CANCELLED',
  confidence DECIMAL(5,4) DEFAULT NULL COMMENT '静态置信分，非运行时收益证明',
  priority INT DEFAULT NULL COMMENT '操作人排序用候选优先级',
  evidence_level VARCHAR(32) NOT NULL COMMENT '证据level：STATIC_PARSE/ACCESS_PARSE/EXPLAIN_PLAN/RUNTIME_HISTORY/BENCHMARK/MIXED',
  schema_version VARCHAR(32) DEFAULT NULL COMMENT '候选载荷模式版本',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '候选创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  source_evidence_json JSON DEFAULT NULL COMMENT '归一化来源证据',
  issue_evidence_json JSON DEFAULT NULL COMMENT '静态解析问题证据',
  runtime_evidence_json JSON DEFAULT NULL COMMENT '仅运行时证据摘要',
  benefit_estimate_json JSON DEFAULT NULL COMMENT '预估收益证据，非真实收益证明',
  cost_estimate_json JSON DEFAULT NULL COMMENT '预估实现或校验成本',
  risk_json JSON DEFAULT NULL COMMENT '风险证据与人工评审提示',
  PRIMARY KEY (candidate_id),
  KEY idx_acc_candidate_tenant_status_created (tenant_id, status, created_at),
  KEY idx_acc_candidate_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_acc_candidate_history (tenant_id, history_id),
  KEY idx_acc_candidate_parse_history (tenant_id, parse_history_id),
  KEY idx_acc_candidate_optimization_task (tenant_id, optimization_task_id),
  KEY idx_acc_candidate_benchmark_task (tenant_id, benchmark_task_id),
  KEY idx_acc_candidate_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_acc_candidate_report (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed acceleration and rewrite candidate persistence';

CREATE TABLE IF NOT EXISTS sql_rewrite_record (
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT 'SQL 改写记录标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联加速推荐标识符',
  optimization_task_id VARCHAR(64) DEFAULT NULL COMMENT '关联optimization task标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '来源族：PARSE/QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '归一化来源类型',
  source_id VARCHAR(128) NOT NULL COMMENT '来源对象标识符',
  evidence_level VARCHAR(32) NOT NULL COMMENT '改写来源证据级别',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  parse_history_id VARCHAR(128) DEFAULT NULL COMMENT '关联sql_parse_历史标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '关联数据源编码',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '改写状态：DRAFT/RECOMMENDED/READY/ACTIVE/PAUSED/FAILED/DEPRECATED/CANCELLED',
  validation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_VALIDATED' COMMENT '校验状态：NOT_VALIDATED/VALIDATING/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  auto_apply_allowed TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示治理允许自动应用',
  manual_review_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示应用前需要人工评审',
  review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW' COMMENT '人工评审状态：PENDING_REVIEW/APPROVED/REJECTED/CHANGES_REQUESTED',
  review_note VARCHAR(512) DEFAULT NULL COMMENT '批准或驳回的人审备注',
  reviewed_by VARCHAR(64) DEFAULT NULL COMMENT '人工评审人标识符',
  reviewed_at DATETIME DEFAULT NULL COMMENT '人工评审时间戳',
  activation_status VARCHAR(32) NOT NULL DEFAULT 'INACTIVE' COMMENT '激活状态：INACTIVE/ACTIVATING/ACTIVE/PAUSED/PAUSING/PAUSE_FAILED/ACTIVATE_FAILED',
  runtime_binding_id VARCHAR(64) DEFAULT NULL COMMENT 'query-execution 内的运行时改写绑定标识符',
  runtime_binding_at DATETIME DEFAULT NULL COMMENT '运行时绑定时间戳',
  runtime_binding_by VARCHAR(64) DEFAULT NULL COMMENT '运行时绑定操作人标识符',
  runtime_binding_scope VARCHAR(128) DEFAULT NULL COMMENT '运行时绑定范围，例如租户和 SQL 指纹',
  activated_sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '激活到运行时绑定的 SQL 指纹',
  runtime_rule_version VARCHAR(64) DEFAULT NULL COMMENT 'query-execution 返回的运行时改写规则版本',
  validation_policy_id VARCHAR(64) DEFAULT NULL COMMENT '校验策略标识符',
  last_validation_run_id VARCHAR(64) DEFAULT NULL COMMENT '最近一次校验运行标识符',
  last_compared_at DATETIME DEFAULT NULL COMMENT '最近一次对比时间戳',
  alert_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '告警状态：NONE/OPEN/ACKED/RESOLVED/SUPPRESSED',
  original_sql_text MEDIUMTEXT NOT NULL COMMENT '用于治理差异对比和追踪的原始 SQL 文本',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '用于治理差异对比和追踪的推荐 SQL 文本',
  executed_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '存在受治理应用路径时的已执行 SQL 文本',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '记录创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  rule_chain_json JSON DEFAULT NULL COMMENT '已应用改写规则链证据',
  diff_summary_json JSON DEFAULT NULL COMMENT '差异摘要证据',
  risk_json JSON DEFAULT NULL COMMENT '风险与评审证据',
  trace_refs_json JSON DEFAULT NULL COMMENT '跨服务追踪引用',
  PRIMARY KEY (rewrite_record_id),
  KEY idx_rewrite_record_tenant_status_created (tenant_id, status, created_at),
  KEY idx_rewrite_record_review (tenant_id, review_status, created_at),
  KEY idx_rewrite_record_activation (tenant_id, activation_status, updated_at),
  KEY idx_rewrite_record_validation (tenant_id, validation_status, last_compared_at),
  KEY idx_rewrite_record_recommendation (tenant_id, recommendation_id),
  KEY idx_rewrite_record_optimization_task (tenant_id, optimization_task_id),
  KEY idx_rewrite_record_source (tenant_id, source_type, source_kind, source_id),
  KEY idx_rewrite_record_history (tenant_id, history_id),
  KEY idx_rewrite_record_parse_history (tenant_id, parse_history_id),
  KEY idx_rewrite_record_fingerprint (tenant_id, sql_fingerprint),
  KEY idx_rewrite_record_runtime_binding (tenant_id, runtime_binding_id),
  KEY idx_rewrite_record_last_run (tenant_id, last_validation_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite record persistence';

CREATE TABLE IF NOT EXISTS rewrite_validation_run (
  validation_run_id VARCHAR(64) NOT NULL COMMENT '改写校验运行标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT '引用的改写记录标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联加速推荐标识符',
  history_id VARCHAR(64) DEFAULT NULL COMMENT '关联治理查询历史标识符',
  sql_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '归一化 SQL 指纹',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '运行状态：PENDING/RUNNING/SUCCEEDED/FAILED/CANCELLED',
  comparison_status VARCHAR(32) NOT NULL DEFAULT 'NOT_COMPARED' COMMENT '对比状态：NOT_COMPARED/EQUIVALENT/DIVERGED/FAILED/EXPIRED',
  difference_type VARCHAR(64) NOT NULL DEFAULT 'NONE' COMMENT '差异类型：NONE/SCHEMA_DIFF/ROW_COUNT_DIFF/KEY_SET_DIFF/ORDER_DIFF/VALUE_DIFF/CHECKSUM_DIFF/TIMEZONE_OR_PRECISION_DIFF/UNKNOWN',
  auto_apply_paused TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示校验已暂停自动应用',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '校验开始时间戳',
  finished_at DATETIME DEFAULT NULL COMMENT '校验结束时间戳',
  comparison_policy_json JSON DEFAULT NULL COMMENT '校验策略快照',
  original_result_digest_json JSON DEFAULT NULL COMMENT '原始 SQL 结果摘要，非完整结果集',
  recommended_result_digest_json JSON DEFAULT NULL COMMENT '推荐 SQL 结果摘要，非完整结果集',
  difference_sample_json JSON DEFAULT NULL COMMENT '有限差异样本证据',
  execution_evidence_json JSON DEFAULT NULL COMMENT '只读执行或压测证据摘要',
  PRIMARY KEY (validation_run_id),
  KEY idx_validation_run_rewrite_started (tenant_id, rewrite_record_id, started_at),
  KEY idx_validation_run_recommendation (tenant_id, recommendation_id),
  KEY idx_validation_run_history (tenant_id, history_id),
  KEY idx_validation_run_status_started (tenant_id, status, started_at),
  KEY idx_validation_run_comparison (tenant_id, comparison_status, difference_type),
  KEY idx_validation_run_fingerprint (tenant_id, sql_fingerprint)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governed SQL rewrite validation run persistence';

CREATE TABLE IF NOT EXISTS runtime_rewrite_binding (
  runtime_binding_id VARCHAR(64) NOT NULL COMMENT 'query-execution 持有的运行时改写绑定标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  rewrite_record_id VARCHAR(64) NOT NULL COMMENT '已激活 sql_rewrite_record 标识符',
  recommendation_id VARCHAR(64) DEFAULT NULL COMMENT '关联推荐标识符',
  source_type VARCHAR(32) NOT NULL COMMENT '改写来源类型，例如 PARSE 或 QUERY',
  source_kind VARCHAR(64) NOT NULL COMMENT '改写来源种类',
  source_id VARCHAR(128) NOT NULL COMMENT '改写来源对象标识符',
  sql_fingerprint VARCHAR(128) NOT NULL COMMENT '用于运行时查找的原始 SQL 指纹',
  original_sql_digest VARCHAR(128) NOT NULL COMMENT '原始 SQL 摘要或摘要哈希',
  original_sql_text MEDIUMTEXT DEFAULT NULL COMMENT '激活时生成改写规则程序的原始 SQL 模板',
  recommended_sql_text MEDIUMTEXT NOT NULL COMMENT '该绑定生效时要应用的已激活 SQL 模板文本',
  rewrite_match_mode VARCHAR(64) NOT NULL DEFAULT 'EXACT_FINGERPRINT' COMMENT '运行时改写匹配模式：EXACT_FINGERPRINT/TEMPLATE_CONDITION_REPLAY',
  rewrite_program_json MEDIUMTEXT DEFAULT NULL COMMENT '参数化改写模板、谓词来源、适用前置条件与风险边界证据',
  template_family_fingerprint VARCHAR(128) DEFAULT NULL COMMENT '忽略可重放 WHERE 条件后的模板族指纹',
  runtime_match_object_refs_json JSON DEFAULT NULL COMMENT '激活时原 SQL 表面对象引用快照，仅用于运行时匹配边界',
  runtime_match_object_names_json JSON DEFAULT NULL COMMENT '激活时原 SQL 表面对象名集合，禁止写入展开后的底层表作为匹配键',
  analysis_physical_object_refs_json JSON DEFAULT NULL COMMENT '解析推荐阶段展开的底层物理对象证据，仅用于分析验证',
  metadata_snapshot_version VARCHAR(128) DEFAULT NULL COMMENT '激活校验使用的元数据快照版本',
  view_definition_hash VARCHAR(128) DEFAULT NULL COMMENT '激活校验使用的 view definition hash',
  metadata_degradation_reason VARCHAR(512) DEFAULT NULL COMMENT '元数据不可用、过期或降级的原因快照',
  datasource_code VARCHAR(128) NOT NULL COMMENT '运行时数据源或方言证据',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '运行时改写绑定状态：ACTIVE/PAUSED',
  rule_version BIGINT NOT NULL DEFAULT 1 COMMENT '每租户与 SQL 指纹单调递增的运行时规则版本',
  runtime_rule_version VARCHAR(64) NOT NULL COMMENT '返回给 sql-optimization 的外部运行时规则版本',
  activated_by VARCHAR(64) NOT NULL COMMENT '激活操作人或服务主体',
  activated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '激活时间戳',
  paused_by VARCHAR(64) DEFAULT NULL COMMENT '暂停操作人或服务主体',
  paused_at DATETIME DEFAULT NULL COMMENT '暂停时间戳',
  pause_reason VARCHAR(512) DEFAULT NULL COMMENT '暂停原因',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  active_binding_key VARCHAR(320) GENERATED ALWAYS AS (
    CASE WHEN status = 'ACTIVE' THEN CONCAT(tenant_id, '::', sql_fingerprint) ELSE NULL END
  ) STORED,
  PRIMARY KEY (runtime_binding_id),
  UNIQUE KEY uk_runtime_rewrite_active_binding (active_binding_key),
  KEY idx_runtime_rewrite_tenant_fingerprint (tenant_id, sql_fingerprint, status),
  KEY idx_runtime_rewrite_tenant_status (tenant_id, status),
  KEY idx_runtime_rewrite_template_family (tenant_id, template_family_fingerprint, status),
  KEY idx_runtime_rewrite_record (tenant_id, rewrite_record_id),
  KEY idx_runtime_rewrite_version (tenant_id, sql_fingerprint, rule_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Query-execution production runtime SQL rewrite binding truth';

CREATE TABLE IF NOT EXISTS dispatch_event (
  dispatch_event_id VARCHAR(64) NOT NULL COMMENT '分发事件标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  recommendation_id VARCHAR(64) NOT NULL COMMENT '来源推荐标识符',
  dispatch_type VARCHAR(32) NOT NULL COMMENT '分发类型：REWRITE_SQL/ACCELERATION_SQL/CREATE_TABLE_SQL/PREWARM_SQL/MAINTENANCE_SQL',
  dispatch_payload_json JSON NOT NULL COMMENT '面向外部装载或维护模块的拉取式分发载荷',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '目标执行引擎',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT '目标数据源编码',
  report_code VARCHAR(128) DEFAULT NULL COMMENT '关联 report编码',
  logical_object_key VARCHAR(255) DEFAULT NULL COMMENT '关联逻辑对象键',
  status VARCHAR(32) NOT NULL COMMENT '分发状态：CREATED/PUBLISHED/PULLED/ACKED/FAILED',
  pulled_by VARCHAR(64) DEFAULT NULL COMMENT '拉取事件的外部模块或操作人',
  pulled_at DATETIME DEFAULT NULL COMMENT '拉取时间戳',
  acked_by VARCHAR(64) DEFAULT NULL COMMENT '确认事件的外部模块或操作人',
  acked_at DATETIME DEFAULT NULL COMMENT '确认时间戳',
  failed_by VARCHAR(64) DEFAULT NULL COMMENT '标记事件失败的外部模块或操作人',
  failed_at DATETIME DEFAULT NULL COMMENT '失败时间戳',
  result_message TEXT DEFAULT NULL COMMENT '外部模块返回的确认/失败消息',
  status_history_json JSON NOT NULL COMMENT '仅追加状态流转证据',
  created_by VARCHAR(64) DEFAULT NULL COMMENT '分发创建人',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (dispatch_event_id),
  KEY idx_dispatch_event_tenant_status_created (tenant_id, status, created_at),
  KEY idx_dispatch_event_recommendation (tenant_id, recommendation_id),
  KEY idx_dispatch_event_report_code (tenant_id, report_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Pull-based recommendation dispatch state machine';

CREATE TABLE IF NOT EXISTS system_config (
  config_key VARCHAR(128) NOT NULL COMMENT '系统配置键',
  config_value VARCHAR(512) DEFAULT NULL COMMENT '仅非敏感系统配置值',
  sensitive_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '值为 1 表示该值仅存储在密文字段中',
  value_ciphertext TEXT DEFAULT NULL COMMENT '敏感配置值的 AES-256 密文信封',
  value_mask VARCHAR(128) DEFAULT NULL COMMENT '敏感配置值的脱敏预览',
  encryption_algorithm VARCHAR(32) DEFAULT NULL COMMENT '敏感值加密算法',
  encryption_key_id VARCHAR(64) DEFAULT NULL COMMENT '敏感值加密密钥标识符',
  config_type VARCHAR(32) NOT NULL DEFAULT 'STRING' COMMENT '配置类型',
  description VARCHAR(255) DEFAULT NULL COMMENT '配置描述',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Global platform configuration';

CREATE TABLE IF NOT EXISTS report_interface_config (
  config_id VARCHAR(64) NOT NULL COMMENT '报表接口配置标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) DEFAULT NULL COMMENT '匹配的数据源编码，空值表示默认配置',
  stage VARCHAR(32) DEFAULT NULL COMMENT '匹配的环境阶段，空值表示默认配置',
  source_type VARCHAR(32) NOT NULL DEFAULT 'HTTP_API' COMMENT '报表 SQL 来源类型',
  endpoint_code VARCHAR(128) NOT NULL COMMENT '接口编码',
  endpoint_name VARCHAR(255) DEFAULT NULL COMMENT '接口显示名称',
  base_url VARCHAR(1024) DEFAULT NULL COMMENT 'HTTP API 基础 URL',
  path_template VARCHAR(512) NOT NULL DEFAULT '/reports/sql' COMMENT '接口路径模板',
  http_method VARCHAR(16) NOT NULL DEFAULT 'GET' COMMENT 'HTTP 方法',
  report_code_param_name VARCHAR(128) NOT NULL DEFAULT 'report_code' COMMENT '报表编码参数名',
  sql_json_path VARCHAR(255) NOT NULL DEFAULT '$.sql' COMMENT 'SQL 字段 JSONPath',
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '认证模式',
  timeout_ms INT NOT NULL DEFAULT 3000 COMMENT '调用超时时间，单位毫秒',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用标志',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (config_id),
  UNIQUE KEY uk_report_interface_tenant_endpoint (tenant_id, endpoint_code),
  KEY idx_report_interface_match (tenant_id, datasource_code, stage, enabled),
  KEY idx_report_interface_tenant_time (tenant_id, update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance report interface configuration';

CREATE TABLE IF NOT EXISTS redis_rule_source (
  source_id VARCHAR(64) NOT NULL COMMENT 'Redis 规则来源标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  source_name VARCHAR(128) NOT NULL COMMENT '来源显示名称',
  redis_endpoints VARCHAR(1024) DEFAULT NULL COMMENT 'Redis 端点列表',
  redis_namespace VARCHAR(128) NOT NULL DEFAULT 'sqlforge:rules' COMMENT 'Redis 命名空间',
  key_pattern VARCHAR(255) NOT NULL DEFAULT 'jdbc-agent:*' COMMENT '规则 key 匹配模式',
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '认证模式',
  credential_ref VARCHAR(255) DEFAULT NULL COMMENT '外部凭据引用',
  bypass_on_unavailable TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Redis 不可用时是否旁路',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用标志',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (source_id),
  KEY idx_redis_rule_source_tenant_time (tenant_id, update_time),
  KEY idx_redis_rule_source_tenant_enabled (tenant_id, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance Redis rule source configuration';

CREATE TABLE IF NOT EXISTS dispatch_policy (
  policy_id VARCHAR(64) NOT NULL COMMENT '分发策略标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  policy_name VARCHAR(128) NOT NULL COMMENT '策略显示名称',
  dispatch_type VARCHAR(32) NOT NULL DEFAULT 'PULL_ONLY' COMMENT '分发类型',
  target_engine VARCHAR(64) DEFAULT NULL COMMENT '目标执行引擎',
  target_datasource VARCHAR(128) DEFAULT NULL COMMENT '目标数据源',
  ack_mode VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT '确认模式',
  pull_window_seconds INT NOT NULL DEFAULT 60 COMMENT '外部拉取窗口，单位秒',
  max_batch_size INT NOT NULL DEFAULT 100 COMMENT '最大批量条数',
  retry_strategy VARCHAR(64) NOT NULL DEFAULT 'MANUAL_RETRY' COMMENT '重试策略',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用标志',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (policy_id),
  KEY idx_dispatch_policy_tenant_time (tenant_id, update_time),
  KEY idx_dispatch_policy_target (tenant_id, target_engine, target_datasource, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance dispatch policy configuration';

CREATE TABLE IF NOT EXISTS datasource_config (
  datasource_id VARCHAR(64) NOT NULL COMMENT '数据源配置标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  datasource_code VARCHAR(128) NOT NULL COMMENT '数据源业务编码',
  datasource_name VARCHAR(128) DEFAULT NULL COMMENT '数据源显示名称',
  engine_type VARCHAR(32) NOT NULL DEFAULT 'HETU' COMMENT '执行引擎类型，例如 HETU/HIVE/SPARK',
  connection_mode VARCHAR(32) NOT NULL COMMENT '连接模式：JDBC/API/REST/CLIENT/GATEWAY/PROXY',
  stage VARCHAR(32) NOT NULL DEFAULT 'PROD' COMMENT '环境阶段',
  jdbc_url VARCHAR(1024) DEFAULT NULL COMMENT 'JDBC 连接 URL',
  jdbc_driver_class_name VARCHAR(255) DEFAULT NULL COMMENT 'JDBC 驱动类名',
  driver_source_type VARCHAR(32) NOT NULL DEFAULT 'CLASSPATH' COMMENT '驱动来源类型：CLASSPATH/UPLOADED',
  jdbc_driver_artifact_id VARCHAR(64) DEFAULT NULL COMMENT '已绑定的上传驱动制品标识符',
  driver_version_label VARCHAR(128) DEFAULT NULL COMMENT '已绑定驱动版本标签快照',
  driver_sha256 VARCHAR(64) DEFAULT NULL COMMENT '已绑定驱动 sha256 快照',
  driver_load_status VARCHAR(32) DEFAULT NULL COMMENT '已绑定驱动加载状态快照',
  username VARCHAR(255) DEFAULT NULL COMMENT '数据源用户名',
  api_base_url VARCHAR(512) DEFAULT NULL COMMENT 'API 基础 URL',
  client_endpoint VARCHAR(512) DEFAULT NULL COMMENT '客户端端点',
  gateway_endpoint VARCHAR(512) DEFAULT NULL COMMENT '网关端点',
  proxy_endpoint VARCHAR(512) DEFAULT NULL COMMENT '代理端点',
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '认证模式',
  credential_mode VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT '凭据模式',
  credential_ref VARCHAR(255) DEFAULT NULL COMMENT '外部凭据引用',
  credential_mask VARCHAR(128) DEFAULT NULL COMMENT '凭据脱敏预览',
  credential_ciphertext TEXT DEFAULT NULL COMMENT 'AES-256 加密的凭据密文',
  encryption_algorithm VARCHAR(32) DEFAULT NULL COMMENT '凭据加密算法',
  encryption_key_id VARCHAR(64) DEFAULT NULL COMMENT '凭据加密密钥标识符',
  tls_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'TLS 启用标志',
  verify_peer TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'TLS 对端校验标志',
  readonly_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT '只读数据源边界',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用标志',
  timeout_ms INT NOT NULL DEFAULT 3000 COMMENT '连接超时时间，单位毫秒',
  health_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '最近健康状态',
  last_failure_reason VARCHAR(255) DEFAULT NULL COMMENT '最近健康检查失败原因',
  last_checked_at DATETIME DEFAULT NULL COMMENT '最近健康检查时间戳',
  last_check_elapsed_ms BIGINT DEFAULT NULL COMMENT '最近健康检查耗时毫秒数',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (datasource_id),
  UNIQUE KEY uk_datasource_config_tenant_code_engine (tenant_id, datasource_code, engine_type),
  KEY idx_datasource_config_tenant (tenant_id, update_time),
  KEY idx_datasource_config_health (tenant_id, health_status, last_checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Governance datasource connection configuration';

CREATE TABLE IF NOT EXISTS jdbc_driver_artifact (
  artifact_id VARCHAR(64) NOT NULL COMMENT 'JDBC 驱动制品标识符',
  tenant_id VARCHAR(64) NOT NULL COMMENT '所属租户标识符',
  engine_type VARCHAR(32) NOT NULL COMMENT '引擎类型：TRINO/HETU/HIVE',
  driver_class_name VARCHAR(255) NOT NULL COMMENT '驱动主类名',
  version_label VARCHAR(128) NOT NULL COMMENT '版本标签',
  original_file_name VARCHAR(255) NOT NULL COMMENT '原始上传文件名',
  size_bytes BIGINT NOT NULL COMMENT '文件大小，单位字节',
  sha256 VARCHAR(64) NOT NULL COMMENT '文件 sha256 校验和',
  relative_path VARCHAR(512) NOT NULL COMMENT '共享卷相对路径',
  status VARCHAR(32) NOT NULL COMMENT '制品状态：READY/FAILED',
  uploaded_by VARCHAR(64) DEFAULT NULL COMMENT '上传操作者标识符',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (artifact_id),
  KEY idx_jdbc_driver_artifact_tenant_time (tenant_id, create_time),
  KEY idx_jdbc_driver_artifact_tenant_engine (tenant_id, engine_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Append-only uploaded JDBC driver artifacts';

CREATE TABLE IF NOT EXISTS system_dictionary (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '字典主键',
  dictionary_type VARCHAR(64) NOT NULL COMMENT '字典类别',
  dictionary_code VARCHAR(64) NOT NULL COMMENT '字典编码',
  dictionary_name VARCHAR(128) NOT NULL COMMENT '显示名称',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '显示顺序',
  enabled_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1 表示启用，0 表示禁用',
  remark VARCHAR(255) DEFAULT NULL COMMENT '字典备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间戳',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间戳',
  PRIMARY KEY (id),
  UNIQUE KEY uk_system_dictionary_type_code (dictionary_type, dictionary_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='System dictionary for enums and display mappings';
